### ISSUE TITLE
Cryptic error using webpack v2, webpack-dev-server v2, RHL v3

### ISSUE THREAD

**Issue by nylen** [gaearon/react-hot-loader#342] opened 2016-08-16 02:41 UTC
In the process of upgrading a project to webpack v2, webpack-dev-server v2, react-hot-loader v3, and d3.js v4 (to take advantage of the new tree shaking features), I ran into the following error:

> React.createElement: type should not be null, undefined, boolean, or
number. It should be a string (for DOM elements) or a ReactClass (for
composite components). Check the render method of `AppContainer`

> Uncaught Invariant Violation: Element type is invalid:
expected a string (for built-in components) or a class/function (for
composite components) but got: object. Check the render method of
`AppContainer`.

I was able to reproduce the error in https://github.com/redmountainmakers/kilntroller-ui/commit/985f14d655b5a712c4ef663c8858eb661f5c4a0d by simply adding a line `undefinedFunctionCall()` to the code.  No indication was given as to the real nature of the error - when it originally showed up, I had to downgrade to webpack v1 to diagnose and fix it in development mode.

Steps to reproduce:

```sh
git clone https://github.com/redmountainmakers/kilntroller-ui
cd kilntroller-ui/
git checkout webpack-2-error 
npm install
make run
# visit localhost:3000 and look at the console
```

Since there is a lot of code involved in making all this work, I'm not sure if this is the right repo to report this error against.

I'm not sure if this is related but it was also unexpected that one of my components' `componentWillUnmount` method was called without the corresponding `componentDidMount` being called first.  In the commit I referenced above, I added some debugging statements to mark the methods in question.

**Comment by HriBB** [comment] 2016-08-16 07:25
Ohhh how I hate that error :)

**Comment by arcanis** [comment] 2016-08-17 21:31
I also have this error. In order to have the actual error, I have to put a breakpoint on the following line:

```js
return React.createElement(this.props.errorReporter, { error: error });
```

It seems that `errorReporter` is `null` for some reason, and we have to inspect the `error` variable manually.

**Comment by calesce** [comment] 2016-09-03 15:04
This seems to be the same issue as #312, want to confirm this is fixed in `3.0.0-beta.3`?

**Comment by nathanmarks** [comment] 2016-09-03 17:08
@calesce One thing I noticed, I don't know if this is redbox related but I'm not getting sourcemapped stacktraces in redbox. When I switch to vanilla error handling (console, no redbox) I get stacktraces. Have you experienced this?

**Comment by calesce** [comment] 2016-09-03 17:35
@nathanmarks Yeah, I'm seeing the same thing. I believe it should be handled by Redbox. Interestingly, on their README they recommend adding `output.devtoolModuleFilenameTemplate` to the webpack config and using `devtool: 'eval'`. I always used `cheap-module-eval-source-map` without many issues.

I also thought that the source maps worked for RHL3 Redbox previously, but maybe I'm mis-remembering.

**Comment by calesce** [comment] 2016-09-03 17:51
@nathanmarks Ok, it looks like Redbox stack traces are only sourcemapped with `devtool: eval`, but then you lose source maps in browser devtools... I guess for now it's pick one or the other.

**Comment by nathanmarks** [comment] 2016-09-04 14:14
@calesce That's a bit rubbish. How do you feel about removing redbox as the default error reporter and using the console instead?

**Comment by calesce** [comment] 2016-09-04 21:17
@nathanmarks Yeah I'd like to see if there's a workaround first (or at the very least at least do `console.log` as well), but I'd probably agree.

**Comment by dreyks** [comment] 2016-09-05 22:39
@calesce the issue is fixed in `3.0.0-beta.3`

**Comment by calesce** [comment] 2016-09-07 01:30
Thanks, @dreyks. @nylen/@arcanis, can you see whether it solved your issues?

**Comment by calesce** [comment] 2016-09-14 00:23
@nathanmarks: We should probably move this to another thread, but I think Redbox will probably be best for now, even though it's not perfect.

Adding console reporting won't be any better, since the stack trace will still be bad with `devtool: 'source-map'`, and the file context in the console will now come from `AppContainer.dev.js` instead of where the original error was thrown.

See `error.stack` in Chrome:
<img width="1433" alt="screen shot 2016-09-13 at 7 21 44 pm" src="https://cloud.githubusercontent.com/assets/5377524/18495951/5aa0368a-79e7-11e6-95ff-3779059d85d8.png">

Also, I'm going to close this issue, since this was fixed in the latest beta.

**Closed by calesce** 2016-09-14 00:23 UTC

**Comment by nylen** [comment] 2016-09-28 03:25
Confirmed that upgrading `react-hot-loader` fixed the issue for me.  Thanks for fixing it!
