### ISSUE TITLE
Cannot read property 'children' of undefined & styles not updating

### ISSUE THREAD

**Issue by talwoolf** [gaearon/react-hot-loader#117] opened 2015-04-11 00:12 UTC
I keep getting this error when adding and removing styles from my React js file.

When I change sass file locations the hot loader seems to work fine and update the page, if I comment out the require statement, webpack compiles as usual but the page fails to update.

Is this something to do with the style loader? if so, why does it only fail when removing styles and not when changing between sass files.

in my React App.js file I have:
```if (process.env.BROWSER) {
    require("./../styles/bg2.scss");
}```

and my setup is as follows:

```
import path 				from 'path';
import webpack 				from 'webpack';
import { host as WP_HOST } 	from './host.js';
import { port as WP_PORT } 	from './host.js';

const contentBase = path.join( path.resolve( './' ), '/public' );

export default {
	devtool 		: 'eval',
	debug 			: 'true',
	hotComponents 	: true,
	cache 			: false,
	watch   		: true, 

	entry   : { 
		'bundle' : [ 
			`./app/browser.js`,
			`webpack-dev-server/client?http://${WP_HOST}:${WP_PORT}`,
			`webpack/hot/only-dev-server`,
		]
	},

	output : {
		filename 				: `[name].js`,
		chunkFilename 			: `[name]-[chunkhash].js`,
		path 					:  contentBase,
		publicPath  			: `http://${WP_HOST}:${WP_PORT}/assets/`,
		hotUpdateMainFilename	: `update/[hash]/update.json`,
		hotUpdateChunkFilename  : `update/[hash]/[id].update.js`
	},

	module : {
		loaders: [
	      { test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.ttf$|\.wav$|\.mp3$/, loader: "file-loader"},
	      { test: /\.js$/, exclude: /node_modules/, loaders: ["react-hot", "babel"] },
	      { test: /\.scss$/, loader: "style!css!sass" }
	    ]
	},

	progress : true,

	plugins : [
		new webpack.HotModuleReplacementPlugin(),
		new webpack.NoErrorsPlugin(),

		new webpack.DefinePlugin({
	        "process.env": {
		        BROWSER 	: JSON.stringify(true),
		        NODE_ENV 	: JSON.stringify("development")
	        }
	    }),

		new webpack.ProgressPlugin((percentage, message) => {
	      const MOVE_LEFT = new Buffer("1b5b3130303044", "hex").toString();
	      const CLEAR_LINE = new Buffer("1b5b304b", "hex").toString();
	      process.stdout.write(`${CLEAR_LINE}${Math.round(percentage * 100)}%: ${message}${MOVE_LEFT}`);
	    }),

		new webpack.optimize.DedupePlugin(),
		new webpack.optimize.OccurenceOrderPlugin()
	]

}
```

**Comment by gaearon** [comment] 2015-04-14 10:49
Can you put up a project reproducing this?

**Comment by gaearon** [comment] 2015-05-21 09:54
I'm closing, but I'll be happy to look into this if you provide a sample project.

**Comment by shane13hsi** [comment] 2015-07-29 03:52
Hi, @gaearon， I’ve got the same problem. You can reproduce the error by:

1. commenting the line https://github.com/shane13hsi/bee/blob/master/src/components/Navbar.js#L1
2. uncomment 
3. see the log in chrome dev tool

Thank you advance.

**Comment by gaearon** [comment] 2015-08-05 23:15
Let's keep it open for further investigation later.

**Comment by gaearon** [comment] 2015-08-22 21:20
I'm closing because this is not React Hot Loader issue. Please file it with Webpack if you still have it.

**Closed by gaearon** 2015-08-22 21:20 UTC

**Comment by hiattp** [comment] 2015-08-28 03:21
Seeing this as well, is this active as an issue in Webpack somewhere? Just found [this](https://github.com/webpack/webpack/issues/682), now closed.
