### ISSUE TITLE
`myFunc = () => {}` doesn't work (?)

### ISSUE THREAD

**Issue by kud** [gaearon/react-hot-loader#564] opened 2017-05-11 16:48 UTC
Hey,

I've got a little problem with hot-loader (I've got the latest version)).

If I do this:

```javascript
renderA() = {
  return (<div />)
}

render() {
  return (
    {this.renderA()}
  )
}
```

it refreshes correctly the render.

But if I do the trick to keep the right `this`:

```javascript
renderA = () => {
  return (<div />)
}

render() {
  return (
    {this.renderA()}
  )
}
```

Nothing happens about the render.

Is it normal?

**Comment by kud** [comment] 2017-05-11 16:52
Related https://github.com/gaearon/react-hot-loader/issues/242

**Comment by MaxInMoon** [comment] 2017-05-21 12:30
@kud did you try this?

```
renderA = () => {
  return (<div />)
}
```

**Comment by gajus** [comment] 2017-05-24 10:11
Duplicate of https://github.com/gaearon/react-hot-loader/issues/554

**Closed** 2017-09-17 15:48 UTC
