### ISSUE TITLE
Problem migrating to v3

### ISSUE THREAD

**Issue by dcosson** [gaearon/react-hot-loader#473] opened 2017-02-03 00:55 UTC
I'm trying to migrate to v3, and am following directions here https://github.com/gaearon/react-hot-loader/issues/243#issuecomment-211957140 which were the most full-fledged I could find.

I'm not sure how to interpret a couple of lines. For steps 2 & 3, if I do want React Hot Loader to preserve state should I still also be setting up `module.hot` to re-render the root component?

I've tried it both ways, when I don't have module.hot I get a warning on every change that it can't update because it would require a full reload and nothing happens.  When I do add module.hot, the state is not preserved and the whole page re-renders on every change (even though I've done all of step 3). In this latter case there's a react-router error when the hot reload happens that says `Warning: [react-router] You cannot change <Router routes>; it will be ignored`, not sure if that's related.

Hoping someone can point me in the right direction (or perhaps there's a bug using this with react router?)

**Comment by mutsys** [comment] 2017-02-03 06:52
@dcosson I don't know if that warning message is the cause of your issue but as it just so happens, I found a work around for that tonight.

## produces the warning message
```
import App from "./app";

const renderRouterWithAppContainer = () => {
    render((
        <AppContainer>
            <Router history={ browserHistory }>
                <Route path="/" component={ App }/>
            </Router>
        </AppContainer>
    ),  document.getElementById("app"));
};

renderRouterWithAppContainer();

if (module.hot) {
    module.hot.accept("./app", () => renderRouterWithAppContainer());
}
```

## does not produce the warning message
```
import App from "./app";

const router = (
    <Router history={ browserHistory }>
        <Route path="/" component={ App }/>
    </Router>
);

const renderRouterWithAppContainer = () => {
    render((
        <AppContainer>
            { router }
        </AppContainer>
    ),  document.getElementById("app"));
};

renderRouterWithAppContainer();

if (module.hot) {
    module.hot.accept("./app", () => renderRouterWithAppContainer());
}
```

In my limited experience so far, it seems that RHL is kind of touchy when React Router is in the mix. What I have observed is that it only seems to work when `<AppContainer/>` is the parent of `<Router/>`. Reversing that parent/child ordering always seems to result in failure.

**Comment by calesce** [comment] 2017-02-11 20:07
Yes, the warning message is something in React Router 2/3 that probably won't be removed (not an issue with RHL). The known RR issues are mostly covered by #249 and #288, so I'm going to close this.

**Closed by calesce** 2017-02-11 20:07 UTC
