### ISSUE TITLE
react-hot-loader doesn't work with class properties

### ISSUE THREAD

**Issue by lili21** [gaearon/react-hot-loader#695] opened 2017-11-14 07:53 UTC
### Description

can not update state within function which is defined with **class properties** style.

### Expected behavior

`this.setState` should update the state.

### Actual behavior

`this.setState` does work as expected.

### Environment

React Hot Loader version: 3.1.2

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.5.0
2. `npm -v`: 5.4.2

Then, specify:

1. Operating system: macOS Sierra 10.12.6
2. Browser and version: Chrome 62.0.3202.89 (64bit)

### Reproducible Demo

[demo](https://github.com/lili21/react-hot-loader-issue)

**Comment by theKashey** [comment] 2017-11-14 11:39
Actually, the problem is another - the "real" arrow function does not work at all. They are updating the `real` component, not the `used`(proxy) one.
See: https://github.com/gaearon/react-hot-loader/issues/662, https://github.com/gaearon/react-hot-loader/issues/686
The possible solution is still in testing. Meanwhile, just don't use env plugin - transpile arrow functions back to es5.

**Comment by lili21** [comment] 2017-11-14 13:56
Thanks for that.

**Comment by neoziro** [comment] 2017-12-26 18:21
Will be fixed in [React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next). I close it because it is a duplicate.

**Closed by neoziro** 2017-12-26 18:21 UTC
