### ISSUE TITLE
Caution when using dlls with webpack

### ISSUE THREAD

**Issue by wmertens** [gaearon/react-hot-loader#526] opened 2017-03-24 19:30 UTC
### Description

Not sure what to do with it but I thought I'd at least report it. I just spent a significant amount time chasing why hot reloading was not working, and I found out that I was too enthusiastic in moving libraries to DLLs.

So the symptoms were that Webpack's Hot Module Reload was working, but all components were getting remounted instead of re-rendered.

I finally traced it down to the babel registration that failed, because `__REACT_HOT_LOADER__` was not defined. Removing react-hot-loader from my list of DLLs fixed it.

I wonder how this can be detected in the future; perhaps a warning should be printed if `__REACT_HOT_LOADER__` is not defined? Or the hot loader functionality should be retrieved via `require`?

**Comment by neoziro** [comment] 2017-09-19 20:15
Duplicate of #627, we need to clarify it in documentation.

**Closed by neoziro** 2017-09-19 20:15 UTC
