### ISSUE TITLE
4.3.12 breaks polyfills for IE11

### ISSUE THREAD

**Issue by joacim-boive** [gaearon/react-hot-loader#1099] opened 2018-11-08 09:06 UTC
### Description

Upgrading from 4.3.11 to 4.3.12 breaks polyfilling for IE11.

### Expected behavior

It should continue to work. :)

### Actual behavior

No error messages during build but polyfills stops working.
They seem to be in the code but not executing or something. 

### Environment

React Hot Loader version: 4.3.12
webpack 4.25.1
@babel/preset-env 7.1.5

Run these commands in the project folder and fill in their results:

1.  `node -v`: 10.13.0
2.  `npm -v`: 6.4.1

Then, specify:

1.  Operating system: macOS Mojave
2.  Browser and version: IE 11

### Reproducible Demo

No repo at this time - sorry. :(

**Comment by skarjalainen** [comment] 2018-11-08 11:12
This file:
https://github.com/gaearon/react-hot-loader/blob/master/src/proxy/createClassProxy.js
Uses string method that IE11 does not support:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

I see error in IE11 console:
SCRIPT438: Object doesn't support property or method 'startsWith'

**Comment by theKashey** [comment] 2018-11-08 11:33
I'll release a fix tomorrow. It's to late for me to draft any release today.

**Comment by theKashey** [comment] 2018-11-11 06:13
Fell free to upgrade to 4.4.0-1 (beta). It fixes this and another issues.

**Comment by rgllm** [comment] 2018-11-12 10:43
Hi @theKashey,
just tested 4.4.0-1 (beta) and I confirm the issue is solved. However, it gives another error related to the Polyfill.
[Console print](https://d.pr/i/xvjsgf).

**Comment by theKashey** [comment] 2018-11-12 11:16
My bad, sorry

**Comment by rgllm** [comment] 2018-11-13 10:36
Sorry for asking one more time @theKashey. Do you have any time expectations to solve this?

**Comment by theKashey** [comment] 2018-11-14 11:40
🐢 tomorrow morning (GMT+10) 🐌 
Sorry, was partially offline for two days.

**Comment by joacim-boive** [comment] 2018-11-19 11:18
Any updates? :)

**Comment by pfftdammitchris** [comment] 2018-11-19 19:17
This must be the mysterious deadly error for:
https://github.com/gatsbyjs/gatsby/issues/10015

Finally!

**Comment by pfftdammitchris** [comment] 2018-11-19 19:20
Great find! This definitely should be the reason why my app on IE is getting this error.

**Comment by theKashey** [comment] 2018-11-19 22:00
Sorry for delay. I wanted to release this change with another one, but (and this is the nature of RHL) even having all the tests green - it does not work in real. Trying to find problem...

**Comment by theKashey** [comment] 2018-11-21 00:58
Fixed in "next", v4.5.1

**Comment by joacim-boive** [comment] 2018-11-21 06:39
Works great so far! :)

**Comment by theKashey** [comment] 2018-11-21 06:47
:sweet:
So let me just collect some feedback before releasing a new version.

**Comment by theKashey** [comment] 2018-12-13 11:39
4.6.0 is no longer beta.

**Closed by theKashey** 2018-12-13 11:39 UTC
