### ISSUE TITLE
Updates no longer working after fixing syntax error 

### ISSUE THREAD

**Issue by aoshi321** [gaearon/react-hot-loader#390] opened 2016-10-04 14:56 UTC
Hi

In regards to the closed issue https://github.com/gaearon/react-hot-loader/issues/389 and  I am using webpack-dev-middleware/webpack-hot-middleware and I'm still experiencing the same issue.

thanks

Aoshi

**Comment by calesce** [comment] 2016-10-04 15:03
Hi, you can continue the conversation in the same issues after it's closed. Can you provide a simple repository that reproduces the issue? If you want to see a working examples you can look [here](https://github.com/calesce/react-hot-loader-examples).

**Comment by aoshi321** [comment] 2016-10-04 17:19
Hi

I've tried the example you have linked to. That also has the same problem. I edited one of the components. Added a syntax error. Any changes after that are no longer picked up until you refresh.

thanks

**Comment by calesce** [comment] 2016-10-04 18:05
Syntax error or runtime exception? Have an example? RHL isn't able to recover from errors on updates to `render`, see #164.

**Comment by aoshi321** [comment] 2016-10-04 19:24
Added the following error

class Home extends Component {
  render() { £$%£$%£$
    return <div>Hello, world</div>;
  }
}

**Comment by calesce** [comment] 2016-10-04 20:04
@aoshi321: OK, yeah if you refresh after Webpack fails to build, you won't see the error overlay in the browser, just the console. The overlay only appears in hot updates. I can see how that's confusing.

It might be worth opening an issue with `webpack-hot-middleware` to get the syntax error overlay on page refresh (if it's possible/feasible), what would you think @glenjamin?

**Comment by glenjamin** [comment] 2016-10-04 20:31
Interesting question.

It might be possible to load only the overlay, although there isn't an obvious way to get a working webpack build to do that when the intended one is broken.

If we found a way to load a stub with an overlay, I'm not sure whether it could be hot reloaded back into the main application.

**Comment by calesce** [comment] 2016-10-09 18:23
Ok, opened as https://github.com/glenjamin/webpack-hot-middleware/issues/133, thanks for responding @glenjamin!

Closing this one because it's not specific to RHL.

**Closed by calesce** 2016-10-09 18:23 UTC
