### ISSUE TITLE
Hot reloading of functions

### ISSUE THREAD

**Issue by jareknowotka** [gaearon/react-hot-loader#145] opened 2015-06-02 22:43 UTC
I'm trying to figure out how to make reloading work with components declared as functions rather then classes. I follow the simple code from excellent [Eric Elliotts post](https://medium.com/javascript-scene/baby-s-first-reaction-2103348eccdd). Since the component is not created through React.createClass (which will be deprecated), as far as I found in the documentation, I need to make the function hot manually. But I don't know where and how to put it there. In future versions of React components will be declared as [functions](https://github.com/reactjs/react-future/blob/master/01%20-%20Core/03%20-%20Stateless%20Functions.js) rather then classes. Is hot reloading even possible in this scenario?

**Comment by gaearon** [comment] 2015-06-03 10:18
Thanks for bringing this up!

I want to support that. The problem is *determining* which functions actually are component factories. This pattern doesn't make it easy.

I will likely be able to solve it in [react-hotify](https://github.com/gaearon/react-hotify) (the spiritual successor to RHL). A Babel plugin could interpret a function with JSX inside as a likely component, and try to enable hot reloading for it. In fact you can already try to add support for hot reloading functions to react-hotify (it has tests!).

I'm going to leave this open. In a few months this is likely to be solved.

**Comment by TYRONEMICHAEL** [comment] 2015-08-27 13:44
Just wondering if this has been resolved? See it is closed now. Do we have to use ES6 classes for react-hot-realoder to work?

**Comment by TYRONEMICHAEL** [comment] 2015-08-27 13:51
My apologies, I see this has been resolved with 1.0 and the public API.

**Comment by TYRONEMICHAEL** [comment] 2015-09-05 19:29
I am unable to get factory functions to hot reload. I am still getting the message ' The following modules couldn't be hot updated'. I know this is because of the 'isReactClassish' file, but the docs state if the function has a render method, it will automatically be hot by default. I am also not having any luck with Module.makeHot.

    function helloFactory() {
      return {
        render: function() {
          return <span>Hello World</span>;
        }
      };
    }

**Comment by TYRONEMICHAEL** [comment] 2015-09-26 12:52
https://github.com/gaearon/react-transform-boilerplate solves the above issues. Thank you for the awesome work.

**Comment by Cottin** [comment] 2015-09-29 13:20
although, there is no boilerplate for non-babel yet :'(

**Comment by michaelBenin** [comment] 2015-10-11 01:21
Also running into this issue. 

My react components hot reload fine but my other utils are giving me the same message.

Is there a way to reload the page when this happens until hotify is finished?

Thank you.

**Comment by gaearon** [comment] 2015-10-19 12:19
Please wait until React Transform supports stateless components. This will take some time.
After that we can considering backporting a limited version of support for them to React Hot Loader, but this is not very likely.

**Comment by gaearon** [comment] 2015-10-19 12:20
>My react components hot reload fine but my other utils are giving me the same message.

Please note that `The following modules couldn't be hot updated` **does not mean you have this specific issue described in this thread.** This is a very general message meaning the hot update bubbled up, and there was no component midway to handle it. It can happen because you use stateless components and they're not supported by React Hot Loader, but it can also happen due to many other reasons.

**Comment by gaearon** [comment] 2016-02-17 20:15
Please track https://github.com/gaearon/babel-plugin-react-transform/pull/85 if you are interested in this.

**Closed by gaearon** 2016-02-17 20:15 UTC
