### ISSUE TITLE
Hot-loader to server multiple entry points

### ISSUE THREAD

**Issue by haohcraft** [gaearon/react-hot-loader#173] opened 2015-08-05 23:22 UTC
Wondering if it is possible to server multiple entry points here.
Something like:

```
entry: {
        //Application specific code.
        main: [
            `webpack-dev-server/client?http://${config.HOST}:${config.PORT}`, 
            'webpack/hot/only-dev-server',
            './app/base.js',
            './app/main.js'
        ],

        login: [
            `webpack-dev-server/client?http://${config.HOST}:${config.PORT}`, 
            'webpack/hot/only-dev-server',
            './app/base.js',
            './app/login.js'
        ],
    },
    output: {
        path: assetsPath,
        publicPath: `http://${config.HOST}:${config.PORT}/public/dist/`,
        chunkFilename: "[name].js",
        filename: '[name].js',
    },

```

**Comment by patrick91** [comment] 2015-08-10 20:33
Check this issue: https://github.com/gaearon/react-hot-loader/issues/141 :)

**Comment by gaearon** [comment] 2015-08-22 21:08
Closing as duplicate of #141.

**Closed by gaearon** 2015-08-22 21:08 UTC
