### ISSUE TITLE
Hot reload breaking for components rendered with ReactDOM.unstable_renderSubtreeIntoContainer

### ISSUE THREAD

**Issue by ryanheathers** [gaearon/react-hot-loader#497] opened 2017-03-03 00:07 UTC
### Description

We are using [React Portal](https://github.com/tajo/react-portal) to render out a model component to `document.body`. Our app is used as a third-party plugin so it is vital for our use case to render modals to `document.body` specifically and not just to `reactroot`.

React Portal uses `ReactDOM.unstable_renderSubtreeIntoContainer` to attach the component to `document.body`. From looking at other libraries such as React Modal, this appears the standard (only?) way in React to force attaching to `document.body`.

However this is currently breaking our Hot Reload setup, **for the modal component only**. The rest of our components are not experiencing this issue. By breaking I mean nothing in the modal component is hot reloaded. Nothing happens, no errors are thrown. Removing the modal from the React Portal wrapper immediately "fixes" the issue. `ReactDOM.unstable_renderSubtreeIntoContainer` pulls the component into a separate `reactroot`, so logically that is probably breaking the link with the hot reload logic setup in our `root.js`.

I expected to find google help on this issue because conceivably this should be a pretty common issue with the popularity of both modals and hot reloading. Yet google is coming up dry. I've also played around with various hot reloading setups with no success.

Can someone point me to any possible solutions for this issue, if it's even solvable?

Many thanks!

### Environment

Can share other setup details if helpful.

**package.json**
```
"react-hot-loader": "^3.0.0-beta.6"
"react-portal": "^3.0.0",
```

**Root.js**
```
import { AppContainer } from 'react-hot-loader';
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import configureStore from './lib/store/store';
import App from './App';

const store = configureStore();

const renderRoot = () => render(
  <AppContainer>
    <Provider store={store}>
      <App />
    </Provider>
  </AppContainer>,
  document.getElementById('root')
);
renderRoot();

if (module.hot) {
  module.hot.accept('./App', renderRoot());
}
```

**Modal.js** (only the important bits)
```
import Portal from 'react-portal';

class Modal extends Component {
  render() {
    return (
       <Portal>
          [Modal Contents]
       </Portal>
    );
  }
```

**Comment by robinvenneman** [comment] 2017-05-02 23:16
Also having some trouble with the HMR sometimes not working but I've tried to reproduce this with a clean [react-hot-boilerplate](https://github.com/gaearon/react-hot-boilerplate/tree/next) setup and adding the `react-portal` modal, seems to work. 
@ryanheathers did you see anything in the console similar to `Ignored an update to unaccepted module ...`? The issue might also be caused by something else, not by `ReactDOM.unstable_renderSubtreeIntoContainer`

**Comment by ryanheathers** [comment] 2017-05-03 23:28
@robinvenneman yep, I've seen console messages similar to that. The root cause is still a mystery to me and unfortunately solving it hasn't been a priority right now. Will try to dig in further at some point.

**Comment by robinvenneman** [comment] 2017-05-04 07:31
@ryanheathers if that is the case then it can be fixed by adding that module to the `module.hot.accept([])` array.

**Comment by neoziro** [comment] 2017-12-25 12:57
Should be solved with [React 16 Portals](https://reactjs.org/docs/portals.html).

**Closed by neoziro** 2017-12-25 12:57 UTC
Labels: help wanted
