### ISSUE TITLE
HotLoader won't work after adding >=2 levels of HoC.

### ISSUE THREAD

**Issue by quangbuule** [gaearon/react-hot-loader#650] opened 2017-10-03 03:33 UTC
Way to reproduce the issue:
- Using this example (`next` branch) https://github.com/gaearon/react-hot-boilerplate/tree/next
- Add `src/HoC.js`
```js
import React, { Component } from 'react';

export function provideHoC() {
  return WrappedComponent => {
    class HoC extends Component {
      render() {
        return <WrappedComponent {...this.props} />
      }
    }

    HoC.displayName = (WrappedComponent.displayName || WrappedComponent.name) + 'WithHOC';
    return HoC;
  };
}
```
- Modify `src/Counter.js`
```diff
 import React, { Component } from 'react';
+import { provideHoC } from './HoC';

-export default class Counter extends Component {
+class Counter extends Component {
   constructor(props) {
    super(props);
    this.state = { counter: 0 };
  }

  componentDidMount() {
    this.interval = setInterval(this.tick.bind(this), 1000);
  }

  tick() {
    this.setState({ counter: this.state.counter + 1 });
  }

  componentWillUnmount() {
    clearInterval(this.interval);
  }

  render() {
    return <h2>Counter: {this.state.counter}</h2>;
  }
}
+
+export default provideHoC()(provideHoC()(Counter));
```

- `npm start` and go to `http://localhost:3000`.
- Modify some text inside `render` method of `Counter`.
- The counter state will be gone.

**Comment by neoziro** [comment] 2017-10-07 07:13
We have to add this to documentation.

**Comment by theKashey** [comment] 2017-10-07 10:48
@neoziro. Never too late. I'll do it.

**Comment by neoziro** [comment] 2017-10-07 18:21
@theKashey done in #655

**Comment by quangbuule** [comment] 2017-10-11 23:46
Hard to fix on huge projects with tons of nested HoCs (since it is proper way to do HoCs). I created babel plugin to solve this:
https://www.npmjs.com/package/extract-hoc

**Comment by theKashey** [comment] 2017-10-12 01:04
@quangbuule - looking quite good, but, please, add tests and a bit more description.

**Comment by neoziro** [comment] 2017-10-12 08:09
This is good, we could eventually integrate it in the project if it is enough stable.

**Comment by quangbuule** [comment] 2017-10-12 14:34
I added some tests here: https://github.com/quangbuule/extract-hoc/blob/master/test/__snapshots__/babel.test.js.snap

**Comment by mateoKaradza** [comment] 2017-10-16 12:08
Still running into this issue, even after using extra-hoc babel plugin and manually extracting HoCs into separate components

Package.json: https://github.com/blazing-edge-labs/admin-playground/blob/master/package.json
Component with HoCs: https://github.com/blazing-edge-labs/admin-playground/blob/master/src/modules/Examples/Profile/Edit/index.js

**Comment by mqklin** [comment] 2017-10-16 12:22
I'm getting the error with this plugin as well.

**Comment by mateoKaradza** [comment] 2017-10-16 12:23
Here are the errors I get:

```
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 ƒ Connect(props, context) {
        _classCallCheck(this, Connect);

        var _this = _possibleConstructorReturn(this, _Component.call(this, props, context));

        _this.version = version;
     …
```

```
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 ƒ Form() {
          var _ref;

          var _temp, _this, _ret;

          _classCallCheck(this, Form);

          for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++)…
```

**Comment by quangbuule** [comment] 2017-10-17 11:23
@mqklin No, the `react-hot-loader` is suppose to be better than previous version/library, but from what I see, developing app with react-transform-hmr is much less painful. There are several cases that your code might have and  won't work with `react-hot-loader`. My library is just to solve the case when you used nested HoC wrappers.

It basically convert this (which not work with `react-hot-loader`):
```js
var FinalComponent = foo()(bar()(TheComponent))
```

to things like this:
```
var FinalComponent_arg1 = bar()(TheComponent);
var FinalComponent = foo()(FinalComponent_arg1);
```

**Comment by theKashey** [comment] 2017-10-17 13:10
@mateoKaradza - just have a look on your project.
First - you did not wrap your App with HotContainer. Next - there is no errors in console. But state is dropping on update :(
According to your message - you have problems with the internals of redux-form.

**Comment by mateoKaradza** [comment] 2017-10-17 13:16
@theKashey thanks for taking a look
Here is the HotContainer for the app: https://github.com/blazing-edge-labs/admin-playground/blob/master/src/index.js#L12

There are no errors in the console because I downgraded version of React Hot Loader, latest version was broken for me, I'd get a message in console saying that the component was updated, but it didn't affect loaded app in the browser (any component). I switched to an older version and now it works fine.

Issue with redux-form is with its initialValues prop. After hot reload, the forms gets re-rendered and it doesn't reload initial values. I saw latests PRs and there was a fix where such functionality can be disabled in development mode, looking forward to test it once they release next version.

**Comment by theKashey** [comment] 2017-10-17 23:04
@mateoKaradza are you expecting redux form to reset values to the initial state on remount? There must be no remount.
Will try to dig your case once again.

PS: 
> Here is the HotContainer for the app: https://github.com/blazing-edge-labs/admin-playground/blob/master/src/index.js#L12

I still can't see it. You just accept changes.
You have to wrap whole application with AppContainer
```js
import { AppContainer } from 'react-hot-loader'; //   <------
const render = Component => {
  ReactDOM.render(
    <AppContainer> <<--- not exists in your code.
      <Component />
    </AppContainer>,
    document.getElementById('root'),
  )
}
```
Without this component `magic` will not work.

**Comment by mqklin** [comment] 2017-10-19 11:53
@quangbuule doest react-transform-hmr work with React16?

**Comment by quangbuule** [comment] 2017-10-23 02:28
@mqklin have no idea, my team haven't used the React 16 yet :).

**Comment by neoziro** [comment] 2017-10-23 14:14
@mqklin I don't think react-transform-hmr works with React 16, but I can't confirm.

**Comment by mqklin** [comment] 2017-10-23 17:39
@neoziro so, as I understand, I can't use RHL3 with decorators, right? Because state is reset on every hot reload?

**Comment by theKashey** [comment] 2017-10-23 23:24
@mqklin - as long there is no "decorators" in JS you can try to add babel plugins
1. babel-plugin-transform-decorators-legacy. Which will convert decorator to a HOC.
2. extract-hoc, which will transform that HOC to the digestible by RHL code.
The order is crucial.

ie
```js
"plugins": [
    "transform-decorators-legacy",
    "extract-hoc/babel",
    "react-hot-loader/babel"
  ]
```

PS: Might not work. Having no chance to properly test it, sorry.

**Comment by transcranial** [comment] 2017-12-11 18:24
https://github.com/quangbuule/extract-hoc solved this issue for me for react-apollo and react-redux HOCs. Would be great if this was integrated somehow.

**Comment by mqklin** [comment] 2017-12-12 09:31
@theKashey @transcranial still `React Hot Loader: this component is not accepted by Hot Loader. ` :(
I feel so frustrated, cause I can't use React16 because of this  
I'm going to create the smallest demo for reproducing, maybe it will help

**Comment by mqklin** [comment] 2017-12-12 10:35
I just tried it with `react-transform-hmr` and got exactly the same problem (works only without decorators). Here is PR: https://github.com/mqklin/rhl3-decorators-bug/pull/1

**Comment by theKashey** [comment] 2017-12-12 11:16
Decorators will not work at all. There is __no way__ to make them work.
Except #711 - it will literally solve everything. I'll do my best to make v4 sorted out before Christmas.

**Comment by neoziro** [comment] 2017-12-25 13:35
A long issue finally fixed in [React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next/).

**Closed** 2018-02-27 10:08 UTC
Labels: bug, fixed in next
