### ISSUE TITLE
Strange behavior - class methods seem to be hijacked / overwritten by RHL?

### ISSUE THREAD

**Issue by AndrewRayCode** [gaearon/react-hot-loader#686] opened 2017-10-22 23:49 UTC
### Description

I have a class like this:

```javascript
export default class ApiClient {
  constructor(req) {
    this.get = function () { console.log("get"); }
    console.log('constructed ', this.get);
  }
}
```

When this class is executed, here's what it logs:
```
constructed  function () {
       return _this.__get__REACT_HOT_LOADER__.apply(_this, arguments);
     }
```

More specifically, I'm doing this in a loop in the constructor, and it gets stranger:
```javascript
export default class ApiClient {
  constructor(req) {
    [ 'get', 'put' ].forEach(method => {
      this[method] = () => { console.log(method); };
    });
    console.log('constructed ', this.get);
    console.log('constructed ', this.put);
  }
}
```

It logs nothing:

```
constructed  undefined
constructed  undefined
```

And when I log the client itself (since downstream code expects `client.get` to exist):

```
created new client ApiClient { method: [Function] } undefined undefined
```

What is going on here? I'm not sure how to debug this, and why my constructor loop isn't running, and why this library is hijacking it.

This is executed in a node server context:

```
app.use((req, res) => {
  if (__DEVELOPMENT__) {
    webpackIsomorphicTools.refresh();
  }
  const client = new ApiClient(req);
```

This code path is also executed by babel on the fly on the server, using `require('babel-register')`

My `.babelrc`:

```
{
  "presets": ["react", "es2015", "stage-0"],

  "plugins": [
    "transform-runtime",
    "add-module-exports",
    "react-hot-loader/babel",
    "transform-decorators-legacy",
    "transform-react-display-name"
  ]
}
```

### Environment

React Hot Loader version: 3.1.1

Run these commands in the project folder and fill in their results:

1. `node -v`: 8.6.0
2. `npm -v`: 5.5.1

**Comment by theKashey** [comment] 2017-10-25 11:38
RHL contain a special logic to "hack" arrow function and inject another context("this") into an arrow function.
That could lead to some issues :(

How  to solve: Find a way to protect a file from RHL's babel plugin.

Not easy doable. First, that comes to my mind - use webpack with 2 babel's profiles. One for jsx(or /components) and RHL inside, and one for the rest of files.

**Comment by neoziro** [comment] 2017-10-25 19:27
@theKashey We need to find a better way to make it work... It is too hacky today. It should not impact code that is not relative to React. Maybe the Babel strategy is not the good one. I will try to take back and think about another solution to do it.

**Comment by theKashey** [comment] 2017-10-26 06:20
@neoziro - I've found a better solution, will provide some code in an hour or two. Everything is quite simple, but better to double check.

**Comment by neoziro** [comment] 2017-10-26 07:57
@theKashey 🤗

**Comment by theKashey** [comment] 2017-10-26 11:22
@neoziro - https://github.com/theKashey/react-stand-in/issues/1

**Comment by AndrewRayCode** [comment] 2017-10-28 18:21
Should this be reflected in the readme, that the fundamental strategy conflicts with non-react code? Not trying to be an ass, but since dan is pointing people to this library, the readme doesn't give any indication about that status (I don't know if "experimental" is the right word?)

**Comment by neoziro** [comment] 2017-10-29 08:30
@AndrewRayCode it is stable but it still has some bugs, must of them are due to the approach (Babel is dangerous). We will try to reduce Babel scope in the next version.

**Comment by Meeeeow** [comment] 2017-11-05 11:48
Following code:
```js
['foo', 'bar', 'barfoo'].map((method) => {
  this[method] = ...
})
```
was transformed to
```js
['foo', 'bar', 'barfoo'].map((method) => {
  this.method = ...
})
```

**Comment by harshes53** [comment] 2017-11-06 11:48
Hi @neoziro, 
is there a way to bypass  RHL `patch` when using `typescript` and targeting `ES6`?

Thanks!

**Comment by theKashey** [comment] 2017-11-06 21:31
@harshes53 - the problem IS with ES6. But you can try to use webpack loader instead of babel plugin. It does not have any magics inside (and that's the problem of loader solution :) )

**Comment by harshes53** [comment] 2017-11-06 21:36
Thanks! 

FYI I don't have any `babel` usage in my project.. so trying to figure out how to use RHL with TS and ES6 target.

**Comment by theKashey** [comment] 2017-11-06 22:11
Heh, good luck.
I am not sure that webpack loader could handle ES6 code. Everything has some limitations.
I'll propose to add babel-loader to your dev webpack configuration, and babel all the things into ES5, at least in dev mode.
ES6 code does not always work due some magic code transforms we are doing, sorry.

**Comment by fwh1990** [comment] 2017-12-01 12:48
Using setState() in callback method will cause a warning by react,
 (`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component.`)

Just happened when my code like :  `export default connect(mapState2Props)(xxxComponent)`. And I bind my callbackFunction in constructor already(`this.handleCallback = this.handleCallback.bind(this);`).

But, if I write my code as : 

@connect() 
export class xxxComponent extend React.Component {}

The warning upon will be gone. However, component's lifecycle will refresh when I change my code, it means that each component will trigger componentWillMount again.

How to fix?

**Comment by fwh1990** [comment] 2017-12-01 12:53
And now , I have to disable rhl, sadly.  By the way, I am using react 16.2, and only support chrome 56+, it means, I didn't transform es6 to 5.

**Comment by theKashey** [comment] 2017-12-01 21:21
@fwh1990 - currently you have to transpile arrow function. To be fixed in next release.

**Comment by neoziro** [comment] 2017-12-26 18:24
Arrow function are no longer transpiled in [React Hot Loader v4](https://github.com/gaearon/react-hot-loader/tree/next).

**Closed** 2018-02-27 10:08 UTC
Labels: bug, fixed in next
