### ISSUE TITLE
[Query/Issue] Devtools error message : React Hot Loader will not hot reload correctly because module definition is wrong.

### ISSUE THREAD

**Issue by aga5tya** [gaearon/react-hot-loader#604] opened 2017-07-12 06:51 UTC
### Environment

React Hot Loader version: **3.0.0-beta.7**

Run these commands in the project folder and fill in their results:

1. `node -v`: v8.1.2
2. `npm -v`: 5.1.0

Then, specify:

1. Operating system: OSX Sierra
2. Browser and version: Chrome v60 beta

-------------------------------------------------------------------------------------------

I'm getting this error in devtools

```
React Hot Loader: Main in /Users/prithviraju/Sites/site/packages/events-client/src/index.js will not hot reload correctly because index.js uses <Main /> during module definition. For hot reloading to work, move Main into a separate file and import it from index.js.
```

Although everything works as expecting with hot reloader. I'm just curious as to what am i doing wrong with the entry point. Kindly advise.

Below is how i have structured the app the entry point.

```
// index.js - App entry point
import React from 'react'
import { render } from 'react-dom'
import BrowserRouter from 'react-router-dom/BrowserRouter'
import Root from 'app/Root'

let initialState = window.__INITIAL_STATE__
let store = configureStore(initialState)

function doRender() {
	render(<Main />, document.getElementById('app'))
}

// Pattern taken from Reactql Kit boilerplate to help eliminate Hot loader in prod builds.
const Main = (() => {
	const Chain = () =>
		<Root
			store={store}
			Router={BrowserRouter}
		/>
        // Webpack uglify drops this during prod builds.
	if (process.env.NODE_ENV === 'development' && module.hot) {
		const AppContainer = require('react-hot-loader').AppContainer
		module.hot.accept('./index.js')
		module.hot.accept('./app/Root', () => {
			require('./app/Root').default
			doRender()
		})

		return () =>
			<AppContainer>
				<Chain />
			</AppContainer>
	}
	return Chain
})()

doRender()
```

```
// Root.js
// @flow

import React from 'react'
import { Provider as ReduxProvider } from 'react-redux'
import App from 'app/modules/App'

let supportsHistory = false
if (__CLIENT__) {
	supportsHistory = 'pushState' in window.history
}

type RootProps = {
	store: any,
	felaRenderer: any,
	Router: any,
	location: string,
	context: any
}

// This component is reused in server rendering. This holds our entry point for server render.
const Root = ({ store, Router, location, context }: RootProps) =>
	<ReduxProvider store={store}>
		<Router
			{...(__CLIENT__
				? { forceRefresh: !supportsHistory }
				: { location, context })}
		>
			<App />
		</Router>
	</ReduxProvider>

export default Root
```

**Comment by initialdmg** [comment] 2017-07-20 03:08
i encounterd this problem, too

**Comment by aga5tya** [comment] 2017-07-20 05:36
@initialdmg I still don't know what causes the issue, but refactoring to the way react-universally loads client and server entrypoint worked for me. Give it a shot.

https://github.com/ctrlplusb/react-universally/blob/master/client/index.js

**Comment by initialdmg** [comment] 2017-07-20 11:56
@aga5tya thanks!  When i got this error, i was using react-redux v3.0.5 that is not quite compatible with react-hot-loader v3. This afternoon, i updated react-redux to v4, and the error was gone. So i guess that might was caused by react-redux.

**Comment by neoziro** [comment] 2017-09-19 19:59
Seems resolved, I close it.

**Closed by neoziro** 2017-09-19 19:59 UTC
