### ISSUE TITLE
[React Hooks] Incompatibility with react-hot-loader

### ISSUE THREAD

**Issue by bkniffler** [gaearon/react-hot-loader#1088] opened 2018-10-26 11:14 UTC
### Description

The new react hooks API does not work with react-hot-loader. Using the [example](https://reactjs.org/docs/hooks-overview.html#-state-hook) in my app with `export default hot(module)(App);` at the bottom of app.js, the following error occurs:

### Expected behavior

Should work.

### Actual behavior

```
Uncaught Error: Hooks can only be called inside the body of a function component.
```

### Reproducible Demo

Dunno of a demo is needed, just ping me if you need one.

**Comment by bkniffler** [comment] 2018-10-26 11:14
Partially related
https://github.com/facebook/react/issues/13972

**Comment by simmo** [comment] 2018-10-26 16:46
Yes I've just seen the same. I tried removing my `hot(module)(App)` equivalent  but also required removing babel plugin to get hooks to work.

**Comment by theKashey** [comment] 2018-10-26 20:44
Yes. RHL is 100% not compatible with hooks. There is just a few reasons behind it:
- SFC are being converted to Class components. There is reason - to be able to `forceUpdate` on HMR, as long there is no "update" method on SFC. I am looking for other way of forcing the update (like [this](https://github.com/facebook/create-react-app/blob/abe07e9538f0d548eefc753949a80376c9b89f8c/packages/react-dev-utils/forceUpdateHook.js#L84). So RHL is __killing SFC__.

- "hotReplacementRender". RHL is trying to do React's job, and render the _old_ and the _new_ app, to merge them. So, obviously, that's broken now.

I am going to draft a PR, to mitigate both problems. It will work, but not today.

**Comment by harisvsulaiman** [comment] 2018-10-29 17:15
This could be a workaround https://github.com/gatsbyjs/gatsby/issues/9489#issuecomment-433872202

**Comment by theKashey** [comment] 2018-10-29 21:22
Next version of RHL, with [16.6 support](https://github.com/gaearon/react-hot-loader/pull/1084) will add `memo` and `lazy` support, and thus break this "fix".
> Right now `memo`-ed components are invisible to RHL, as long they are not functions, but objects.

**Comment by theKashey** [comment] 2018-10-29 21:28
There is a more proper fix, which would work my better and ever after - [cold API](https://github.com/gaearon/react-hot-loader#disabling-a-type-change-%EF%B8%8F)

You may disable RHL for any custom type.
```js
import { cold } from 'react-hot-loader';
cold(MyComponent);
```
or just search for "useState/useEffect" inside component source code, and ❄️it.
```js
import { setConfig, cold } from 'react-hot-loader'
setConfig({
  onComponentRegister: (type, name, file) =>
    (String(type).indexOf('useState') > 0 ||  String(type).indexOf('useEffect') > 0) && cold(type),
})
```

**Comment by theKashey** [comment] 2018-10-29 21:31
Meanwhile, everything depends on this - https://github.com/reactjs/rfcs/pull/74

**Comment by pedronauck** [comment] 2018-10-31 21:57
I just set `pureSFC` and everything works fine, this can be a problem for other pieces @theKashey?

```
setConfig({ pureSFC: true })
```

**Comment by theKashey** [comment] 2018-11-01 02:43
Probably `pureSFC` is a good option. Just
- don't wrap SFC with `hot` - top component should be a component to be able to update nested tree on HMR.
 - don't define contextTypes on it (not a problem for hooks)

**Comment by theKashey** [comment] 2018-11-01 02:58
PS: While we found a way to handle hooks, React.memo and lazy is not yet supported
(https://github.com/gaearon/react-hot-loader/pull/1084)

**Comment by KyleAMathews** [comment] 2018-11-02 01:55
Who's gonna write the Babel plugin which auto adds this if it detects a hook import? 😘

**Comment by theKashey** [comment] 2018-11-02 10:04
Probably me. I already was used to introduce per-component settings to support React.memo, and the same would work for hooks.
I'll release a new version tomorrow, with memo and hooks 🤞, but, probably, without React.Lazy support.

**Comment by theKashey** [comment] 2018-11-02 10:04
Styled-components v4 also reported not to work. One more thing to manage.

**Comment by theKashey** [comment] 2018-11-21 02:13
v4.5.0(next) solves most of 16.6/16.7 issues and could handle anything if you will got your node_modules processed by our webpack-loader.
Please give a try and report back.
PS: If someone could convert webpack loader to webpack plugin - that would be just great.

**Comment by theKashey** [comment] 2018-11-21 11:02
You know, @joepie91, I also was not quite happy of this change. As I mentioned is the storybook issue - there is no way to ask user to include a one more webpack-loader to their configuration.
It's also not doable with Parcel, Electron, CRA and so on...

So I just did a terrible thing (everyone - please blame @joepie91 ) - __forked react-dom__ - https://github.com/hot-loader/react-dom.

Now you may skip webpack-loader stuff, just amend your configuration to use _another_ `react-dom`. As far as I know - this would work only with `aliases` as long as you have to rewire not only your own files, but also node_modules, including react-hot-loader.
```js
// webpack.conf
resolve: {
    alias: {
      'react-dom': '@hot-loader/react-dom',
    .....

// for parcel add `alias` field to the package.json

// not sure about electron
```
This is just a quick spike, currently only for dev version and React-16.7-alpha2 (build is automated, there is no problem to publish more versions, once approach would be proven)

**Comment by Bnaya** [comment] 2018-11-21 13:51
@theKashey there's a yarn "trick" to install package as another name:
https://twitter.com/sebmck/status/873958247304232961?lang=en

**Comment by theKashey** [comment] 2018-11-21 21:44
Then we got all the cases (except npm) covered. I've updated react-🔥-dom, and included production version, as long @Bnaya hack could not be undone for prod builds.

the final configuration could be like:
1. Add webpack-loader or use special version of react-dom.
2. Set configuration
```js
// hotConf.js. Should be imported before any other React stuff
import { setConfig } from 'react-hot-loader'
import ReactDOM from 'react-dom';

setConfig({
  // if our patch is present - ignore all SFC
  ignoreSFC: !!ReactDOM.setHotElementComparator,
  // set this flag to support SFC if patch is not landed
  pureSFC: true,
  // remove side effect on classes, to make react-dev-tools experience better(go-to-source)
  pureRender: true,
})
```
Everything could work even without webpack-loader/react-hot-dom, but it could be strange experience, like React.memo could be not updated. (useMemo will be not updated in any case)

In my tests everything is working. What about you?

**Comment by BerndWessels** [comment] 2018-11-23 02:56
@theKashey I am confused now :(

What is the solution to hot-loading and hooks for `create-react-app` ? `react-app-rewired` ?

I really want to avoid to use a forked react-dom if possible.

**Comment by strobox** [comment] 2018-11-28 14:44
If I use
`
      {
        test: /\.jsx?$/,
        include: /node_modules/,
        use: ['react-hot-loader/webpack'],
      },
`
as sad in readme I  get multiply messages of save error:
_    ERROR in (webpack)/buildin/global.js
    Module build failed (from ./node_modules/react-hot-loader/webpack.js):
    TypeError: aSourceMapConsumer.eachMapping is not a function
        at Function.fromStringWithSourceMap (/Users/chikovvas/activity/code/own/xapnew/node_modules/react-hot-loader/node_modules/source-map/lib/source-node.js:87:24)
        at Object.transform$1 (/Users/chikovvas/activity/code/own/xapnew/node_modules/react-hot-loader/dist/webpack.development.js:132:59)
     @ ./node_modules/html-webpack-plugin/node_modules/lodash/lodash.js 1:0-47
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./client/index.html_

**Comment by theKashey** [comment] 2018-11-30 22:08
> Module not found: Error: Can't resolve 'lodash.merge' in 
Use 4.5.1, not 4.5.0

> TypeError: aSourceMapConsumer.eachMapping is not a function
Something is wrong on mine side :(

**Comment by aaronjensen** [comment] 2018-12-03 23:03
I've got `@hot-loader/react-dom` installed and aliased and the config set up, but I get this when a hot load happens:

```

warning @ browser.js?e834:49
routerWarning @ routerWarning.js?437b:21
Router_componentWillReceiveProps @ Router.js?9ebe:113
callComponentWillReceiveProps @ index.dev.js?2e06:12678
updateClassInstance @ index.dev.js?2e06:12888
updateClassComponent @ index.dev.js?2e06:14379
beginWork @ index.dev.js?2e06:15203
performUnitOfWork @ index.dev.js?2e06:17941
workLoop @ index.dev.js?2e06:17981
renderRoot @ index.dev.js?2e06:18067
performWorkOnRoot @ index.dev.js?2e06:18958
performWork @ index.dev.js?2e06:18870
performSyncWork @ index.dev.js?2e06:18844
requestWork @ index.dev.js?2e06:18713
scheduleWork @ index.dev.js?2e06:18522
enqueueForceUpdate @ index.dev.js?2e06:12466
Component.forceUpdate @ react.development.js?72d0:390
(anonymous) @ react-hot-loader.development.js?c2cb:1942
(anonymous) @ react-hot-loader.development.js?c2cb:1941
setTimeout (async)
updateInstances @ react-hot-loader.development.js?c2cb:1935
(anonymous) @ react-hot-loader.development.js?c2cb:1957
hotSetStatus @ customer.js:248
hotApply @ customer.js:630
cb @ process-update.js?e135:66
(anonymous) @ process-update.js?e135:82
Promise.then (async)
check @ process-update.js?e135:81
module.exports @ process-update.js?e135:42
processMessage @ client.js?fec9:268
handleMessage @ client.js?fec9:136
handleMessage @ client.js?fec9:99
15:02:50.533 index.dev.js?2e06:18812 Uncaught TypeError: scheduler.unstable_shouldYield is not a function
    at shouldYieldToRenderer (index.dev.js?2e06:18812)
    at performAsyncWork (index.dev.js?2e06:18821)
    at flushFirstCallback (scheduler.development.js?3069:128)
    at flushWork (scheduler.development.js?3069:230)
    at idleTick (scheduler.development.js?3069:569)
```

Any hints?

**Comment by theKashey** [comment] 2018-12-04 00:41
@aaronjensen - `sheduler` package is below version 11. 
Possible solutions:
- ensure that you have react-dom@16.7.0 installed
- check `scheduler` version (why it's below)
- (me) copy dependencies from react-dom to `@hot-loader/react-dom` - right now they are empty, and that would not work with complicated package resolution.

**Comment by aaronjensen** [comment] 2018-12-04 06:55
@theKashey thank you, I had an extra `scheduler` due to `react-test-renderer` and two versions of `react` (thanks to an older package incorrectly making `react` a dependency). Also, if you're using `enzyme`, you may need to add this to your `package.json` (assuming yarn):

``` 
  "resolutions": {
    "react-test-renderer": "^16.7.0-alpha.2"
  }
```

Otherwise you could end up with two versions of `react-test-renderer` which could leave you with two versions of `scheduler`.

I no longer get the error, but hot reloading does not work. I see the modules update in the console, but React does not rerender.

To confirm:

1. I am not using the babel plugin
2. I am using `@hot-loader/react`
3. This is my `setConfig`:
    ```
    import { setConfig } from 'react-hot-loader'
    import ReactDOM from 'react-dom'

    setConfig({
      ignoreSFC: !!ReactDOM.setHotElementComparator,
      pureSFC: true,
      pureRender: true,
    })
    ````
4. `ReactDOM.setHotElementComparator` is defined
5. `hot(module)(...)` wraps a class component

Is there anything I'm missing or wrong? I'm sorry if it's something obvious I missed...

**Comment by theKashey** [comment] 2018-12-04 12:01
`cold component ... has been updated` is ok. You configured to ignore SFC, but they got updated - I just need to ignore this situation if `setHotElementComparator` is set. I will fix it.


right now babel(or webpack) plugin is crucial for memo, lazy and forwardRef to work properly. But it should do _something_ even without it.

**Comment by skyboyer** [comment] 2018-12-05 07:34
does it make sense to highlight this thing specifically in the docs for Hooks?

**Comment by ooloth** [comment] 2018-12-05 15:18
Using `setConfig` to enable hooks support (e.g. like the latest version of Gatsby)...

```js
import { setConfig } from "react-hot-loader"

setConfig({
   ignoreSFC: true,
   pureRender: true,
 })
```

...appears to trigger some new `forwardRef` errors (e.g. with some `react-spring` components):

```sh
Warning: Function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `AnimatedComponent`.
```

Everything still works, though, so just checking if these errors can be safely ignored.

(See [this issue](https://github.com/drcmda/react-spring/issues/349#issuecomment-444319983) for more details.)

**Comment by aaronjensen** [comment] 2018-12-05 17:07
FYI, aliasing `react-dom` to `@hot-loader/react-dom` appears to break React Router v3, at least for us.

**Comment by theKashey** [comment] 2018-12-05 21:13
@aaronjensen - could you shed some light? What(How?) is broken?

**Comment by theKashey** [comment] 2018-12-05 21:20
@ooloth - is it with 4.5.0+, our you are still on 4.3.x?

**Comment by theKashey** [comment] 2018-12-06 06:20
I will release an update just when I will figure out what is wrong with @ooloth issue.

**Comment by aaronjensen** [comment] 2018-12-06 06:51
> @aaronjensen - could you shed some light? What(How?) is broken?

@theKashey sorry, I haven't had a chance to dig into it yet. Some of the routes were not working at all. Some did, others didn't. The url would change, but the router would not render the appropriate page.

**Comment by aaronjensen** [comment] 2018-12-06 07:40
AFAICT, this is the minimum repro for the problem:

```js
import React from 'react'
import ReactDOM from 'react-dom'
import { Router, Route, Link, browserHistory } from 'react-router'

const PageA = () => (
  <div>
    Page A <Link to="/page-b">toggle</Link>
  </div>
)

const PageB = () => (
  <div>
    Page B <Link to="/page-a">toggle</Link>
  </div>
)

const Routes = () => (
  <Router history={browserHistory}>
    <Route path="/page-a" component={PageA} />
    <Route path="/page-b" component={PageB} />
  </Router>
)

ReactDOM.render(<Routes />, document.getElementById('app'))
```

Visit `/page-a` then click the toggle link. That will take you to `/page-b` which will render. Click toggle again and it will change the location, but not the content.

If the alias `@hot-loader/react-dom` alias is commented out, it works as expected and you can toggle between both back and forth.

**Comment by theKashey** [comment] 2018-12-06 10:47
Ouch. That explains a lot

**Comment by theKashey** [comment] 2018-12-06 11:36
4.5.2 released. All reported issues solved.

**Comment by aaronjensen** [comment] 2018-12-06 19:55
@theKashey thank you. I was able to get it to work, though I had to replace `react-loadable` with `React.lazy` as I had the same problem w/ components created via `react-loadable`.

For anyone who is in a similar situation, it doesn't seem like `React.lazy` works w/ react-router 3, so I did this:

```ts
import * as React from 'react'

// React router v3 does not appear to support React.lazy components directly, so
// we wrap them in another component.
const load = (loader: () => Promise<any>) => {
  const Component = React.lazy(loader)
  return (props: any) => <Component {...props} />
}

export default load
```

**Comment by theKashey** [comment] 2018-12-06 21:19
"The same problem" - one component rendered instead on another? That's __critical__, and I thought I fixed it... for any component, declared as a top level variable with babel or webpack plugins enabled. Without "variable registration" RHL could merge two classes with the same name, and looking the same.
Look like `LoadableComponent`, created by one `Loadable` got merged with another `LoadableComponent`, created by another. This is how RHL __designed__ to work. I was counting on tree reconciliation on `Loadable`, not sure why it lead to obsolete fiber element comparison.

**Comment by aaronjensen** [comment] 2018-12-06 22:34
> "The same problem" - one component rendered instead on another?

Yes, that's correct afaict. I haven't tried to create a minimum repro, but I'd guess separating page a and b into separate modules and using react-loadable above would do so.

This was what my `load` function looked like:

```ts
import * as React from 'react'
import IconLoading from 'components/icons/loading'
import Loadable from 'react-loadable'

const load = (loader: () => Promise<any>) =>
  Loadable({
    loader,
    // eslint-disable-next-line react/prop-types
    loading: ({ pastDelay }) => (pastDelay ? <IconLoading /> : null),
    delay: 300,
  })

export default load
```

Then I'd do something like:

```
const PageA = load(() => import('./pagea.js'))
```

If that's not enough, please let me know and I'll see if I can come up w/ a repro.


Thanks!

**Comment by theKashey** [comment] 2018-12-07 06:55
So the problem is very simple, and we already fought with it before - the "hot" stuff inside react-dom is always active, always ready to hot-update something, even if there is nothing to. 2 `loadable` components are very similar in real, and should replace each other.
I will whitelist this logic for a `nextTick` after the real HMR event, hope it will solve these false-positives.

**Comment by theKashey** [comment] 2018-12-07 13:18
v4.5.3(or just next) released. False positive _merges_ got fixed, among a set of other problems.
🤞 release candidate.

**Comment by natew** [comment] 2018-12-07 19:45
I'm getting the sourcemap errors again with 4.5.3 (wasn't seeing them with 4.5.2):

```
ERROR in ./src/main.ts
Module build failed (from /Users/nw/projects/motion/orbit/packages/build/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
.inputSourceMap must be a boolean, object, or undefined

    at assertInputSourceMap (/Users/nw/projects/motion/orbit/packages/build/node_modules/@babel/core/lib/config/validation/option-assertions.js:110:11)
    at Object.keys.forEach.key (/Users/nw/projects/motion/orbit/packages/build/node_modules/@babel/core/lib/config/validation/options.js:107:5)
    at Array.forEach (<anonymous>)
    at validateNested (/Users/nw/projects/motion/orbit/packages/build/node_modules/@babel/core/lib/config/validation/options.js:83:21)
    at validate (/Users/nw/projects/motion/orbit/packages/build/node_modules/@babel/core/lib/config/validation/options.js:74:10)
    at loadPrivatePartialConfig (/Users/nw/projects/motion/orbit/packages/build/node_modules/@babel/core/lib/config/partial.js:66:50)
    at Object.loadPartialConfig (/Users/nw/projects/motion/orbit/packages/build/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/nw/projects/motion/orbit/packages/build/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/nw/projects/motion/orbit/packages/build/node_modules/babel-loader/lib/index.js:3:103)
 @ multi (webpack)-dev-server/client?http://localhost:3999 (webpack)/hot/dev-server.js ./src/main null[2]
```

**Comment by theKashey** [comment] 2018-12-07 21:56
🤷‍♂️

**Comment by natew** [comment] 2018-12-07 22:56
Does the patch I sent work for you? It fixed it for me.

**Comment by theKashey** [comment] 2018-12-13 11:40
4.6.0 just went out. No longer beta.

**Comment by ooloth** [comment] 2018-12-13 12:58
@theKashey You rock.

**Comment by natew** [comment] 2018-12-13 17:45
@theKashey the docs for hooks in the readme still seem old?

**Comment by KidkArolis** [comment] 2018-12-13 19:14
I'm test driving the new version. Seems to work ok for the most part.

In one place I'm getting:

```
react-hot-loader.development.js:1534 Uncaught TypeError: oldType[UNWRAP_PROXY] is not a function
    at compareComponents (react-hot-loader.development.js:1534)
    at hotComponentCompare (react-hot-loader.development.js:1558)
    at reconcileSingleElement (react-dom.development.js:13743)
    at reconcileChildFibers (react-dom.development.js:13825)
    at reconcileChildren (react-dom.development.js:14200)
    at updateFunctionComponent (react-dom.development.js:14341)
    at beginWork (react-dom.development.js:15196)
    at performUnitOfWork (react-dom.development.js:17941)
    at workLoop (react-dom.development.js:17981)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
```

Why could that be? I could try to compile a reproducable example, but pretty tricky to extract from the code.

**Comment by KidkArolis** [comment] 2018-12-13 19:17
Ok, I think it's happening specifically when I wrap my import like this:

Works:

```js
import SomeComponent from 'pages/SomeComponent'
const App = () => (
  <SomeComponent />
)
export default hot(App)
```

Does not work:

```js
const SomeComponent = ac(() => import('pages/SomeComponent'))
const App = () => (
  <SomeComponent />
)
export default hot(App)

function ac (importComponent) {
  return function Component (props) {
    const [C, setComponent] = useState()
    useEffect(() => {
      importComponent().then(setComponent)
    }, [])
    return C ? <C.default {...props} /> : null
  }
}
```

I guess it's a bit fancy, but I'm trying to load my pages async. But I'm getting that error from the previous comment.

**Comment by KidkArolis** [comment] 2018-12-14 11:01
Ok, fwiw, if I lazy load components using [React.lazy](https://reactjs.org/blog/2018/10/23/react-v-16-6.html) everything works great. Apologies for the noise on already heavy thread, should have opened a separate issue.

Having said that, would be interesting to understand why that bit of code above throws `oldType[UNWRAP_PROXY] is not a function`, might lead to some bugfix.

**Comment by theKashey** [comment] 2018-12-18 05:44
1 - look like `source-map` went _frontend_ way due to `fetch` polyfill, probably. It's fixed in `0.8.0-beta.0`, which I probably shall not use yet. See https://github.com/mozilla/source-map/issues/349

2 - this error means that you have `ignoreSFC: true`, but not `@hot-loader/react-dom` - it should display a message when _hot-patches_ are detected.

**Comment by digitaltopo** [comment] 2019-01-09 23:12
NOT getting HMR to work with hooks:
![screenshot_2019-01-09_15-00-56](https://user-images.githubusercontent.com/1680796/50935017-6276b800-141f-11e9-9869-4f5d8156194a.png)

Tried to follow the instructions in readme pretty closely, since was expecting [hooks to be supported](https://github.com/gaearon/react-hot-loader/issues/1088#issuecomment-446938770)...

Stacktrace:
```
Uncaught TypeError: Object(...) is not a function
    at Test (test.js:22)
    at mountIndeterminateComponent (react-dom.development.js:14812)
    at beginWork (react-dom.development.js:15317)
    at performUnitOfWork (react-dom.development.js:18151)
    at workLoop (react-dom.development.js:18191)
    at HTMLUnknownElement.callCallback (react-dom.development.js:150)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:200)
    at invokeGuardedCallback (react-dom.development.js:257)
    at replayUnitOfWork (react-dom.development.js:17438)
    at renderRoot (react-dom.development.js:18310)
    at performWorkOnRoot (react-dom.development.js:19166)
    at performWork (react-dom.development.js:19078)
    at performSyncWork (react-dom.development.js:19052)
    at requestWork (react-dom.development.js:18921)
    at scheduleWork (react-dom.development.js:18730)
    at scheduleRootUpdate (react-dom.development.js:19398)
    at updateContainerAtExpirationTime (react-dom.development.js:19426)
    at updateContainer (react-dom.development.js:19483)
    at ReactRoot.render (react-dom.development.js:19775)
    at eval (react-dom.development.js:19915)
    at unbatchedUpdates (react-dom.development.js:19281)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:19911)
    at render (react-dom.development.js:19981)
    at eval (index.js:21)
    at Module../src/index.js (main.js:1417)
    at __webpack_require__ (main.js:724)
    at fn (main.js:101)
    at eval (webpack:///multi_(:8080/webpack)-dev-server/client?:3:18)
    at Object.0 (main.js:1428)
    at __webpack_require__ (main.js:724)
    at main.js:791
    at main.js:794
Test @ test.js:22
mountIndeterminateComponent @ react-dom.development.js:14812
beginWork @ react-dom.development.js:15317
performUnitOfWork @ react-dom.development.js:18151
workLoop @ react-dom.development.js:18191
callCallback @ react-dom.development.js:150
invokeGuardedCallbackDev @ react-dom.development.js:200
invokeGuardedCallback @ react-dom.development.js:257
replayUnitOfWork @ react-dom.development.js:17438
renderRoot @ react-dom.development.js:18310
performWorkOnRoot @ react-dom.development.js:19166
performWork @ react-dom.development.js:19078
performSyncWork @ react-dom.development.js:19052
requestWork @ react-dom.development.js:18921
scheduleWork @ react-dom.development.js:18730
scheduleRootUpdate @ react-dom.development.js:19398
updateContainerAtExpirationTime @ react-dom.development.js:19426
updateContainer @ react-dom.development.js:19483
ReactRoot.render @ react-dom.development.js:19775
(anonymous) @ react-dom.development.js:19915
unbatchedUpdates @ react-dom.development.js:19281
legacyRenderSubtreeIntoContainer @ react-dom.development.js:19911
render @ react-dom.development.js:19981
(anonymous) @ index.js:21
./src/index.js @ main.js:1417
__webpack_require__ @ main.js:724
fn @ main.js:101
(anonymous) @ client:3
0 @ main.js:1428
__webpack_require__ @ main.js:724
(anonymous) @ main.js:791
(anonymous) @ main.js:794
react-dom.development.js:16014 The above error occurred in the <Test> component:
    in Test (created by App)
    in div (created by App)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

Versions:
```
 "react": "^16.7.0-alpha.2"
 "react-hot-loader": "^4.6.3"
"@hot-loader/react-dom": "^16.7.0",
 "webpack": "^4.28.1",
```

* Using `react-hot-loader/babel` in `.babelrc`
* Resolving `'react-dom': '@hot-loader/react-dom'` alias in `webpack.config.js` (confirmed it's loading: `React-Hot-Loader: react-🔥-dom patch detected. You may use all the features.` printed in console)

Here's how I've set my app up:

index.js (root entry)
```
import React from 'react';
import {setConfig} from 'react-hot-loader';
import {render} from 'react-dom';
import App from './core/App';

// Configure RHL
setConfig({
    //pureSFC: true
    ignoreSFC: true, // RHL will be __completely__ disabled for SFC
    pureRender: true // RHL will not change render method
});
render(<App />, document.getElementById('root'));
```
I've also tried without setConfig and with different options enabled/disabled, but always have the same result...

App.js:
```
import React from 'react';
import {hot} from 'react-hot-loader/root';

import Test from '../components/test';

const App = () => (
    <div>
        <h1>Hello React World!</h1>
        <Test />
    </div>
);

export default hot(App);
```

Test.js:
```
import React, {useState} from 'react';

const Test = () => {
    // Declare a new state variable, which we'll call "count"
    const [count, setCount] = useState(0);

    return (
        <div>
            <h2>Test useState hook Functional Component</h2>
            <p>You clicked {count} times</p>
            <button onClick={() => setCount(count + 1)}>Click me</button>
        </div>
    );
};

export default Test;
```
If I remove `useState` everything works and it hot reloads. 

Would appreciate any help!

**Comment by digitaltopo** [comment] 2019-01-10 01:36
Looks like I was able to get everything working using:

* react & react-dom @ `16.8.0-alpha.0`
* `react-hot-loader/babel` babel plugin
* `react-hot-loader/webpack` loader in webpack, instead of (without) `@hot-loader/react-dom` package (this only goes up to 16.7.0-alpha.x)
* Didn't need to use any `setConfig` for `react-hot-loader`

Hot reloading should work in my demo repo for anyone interested: https://github.com/digitaltopo/webpack-4-simple-boilerplate/tree/react-alpha

**Comment by theKashey** [comment] 2019-01-10 04:34
"react-dom" does not support hooks. They are available in alpha-2, or 16.8

**Comment by ntucker** [comment] 2019-02-02 23:41
I'm having troubles when I yarn link a package that uses hooks. It works fine if it's installed normally though. I'm getting the 'classes cannot use hooks' issue

**Comment by theKashey** [comment] 2019-02-03 00:54
@ntucker - you __have__ to specify `pureSFC` or `ignoreSFC` option.
Probably it's time to make one of them default...

**Comment by ntucker** [comment] 2019-02-03 01:11
Or at the very least add that to the instructions? They are quite confusing now with about 4 different ways to do things and it's not clear if they're referring to the same way or old ones. Maybe move ALL outdated methods to other files and just focus on the options for the 'latest way' to do things on the main readme.

**Comment by ntucker** [comment] 2019-02-03 01:12
`React-Hooks should work out of the box if you are using version 4.6.0 or above (pureSFC is enabled by default).`

from the readme. so I guess that's not true @theKashey ?

**Comment by ntucker** [comment] 2019-02-03 01:15
```javascript
import { hot } from 'react-hot-loader/root';
import { setConfig } from 'react-hot-loader';
setConfig({ pureSFC: true });
export default hot(withRouter(App), { errorBoundary: false });
```
Is this how I'm supposed to do it now?

**Comment by ntucker** [comment] 2019-02-03 01:38
You might consider adding https://github.com/gaearon/react-hot-loader/issues/1088#issuecomment-434912466 to the docs.

**Comment by ntucker** [comment] 2019-02-03 02:31
@theKashey well i have hotreloading working perfectly without yarn link, but it is still giving that error even after doing setConfig.

https://github.com/ntucker/anansi/tree/master/examples/typescript is the project. the yarn link is for rest-hooks

**Comment by natew** [comment] 2019-02-07 00:26
Didn't see this anywhere in the comments here or other issues. I'm getting this when I change hooks in a component:

```
Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement
```

Is this a current known issue or limitation or due to an improper config?

**Comment by theKashey** [comment] 2019-02-07 00:38
@natew - try changing the configuration. RHL is trying to re-render updated application, and that "custom" render is not hooks compatible. It was just failing with alpha versions, but it was not a big deal. I didn't test 16.8, and something may change.
```js
setConfig({
disableHotRenderer: true
})
```

**Comment by yoution** [comment] 2019-03-20 05:12
I write a babel plugin for react hooks hot load, it wrap react hooks component with react component, https://github.com/yoution/babel-plugin-react-hooks-hot-load

**Comment by natew** [comment] 2019-03-20 18:01
@yoution so this basically helps hooks HMR without the errors you see if you change them?

**Comment by theKashey** [comment] 2019-03-20 21:43
@yoution - so you are wrapping every hooked-component with `Component`, and thus letting RHL to setup error boundaries around it.
- + would help to isolate error in hooks
- - is not __forwarding refs__.

I am thinking about _proxy-regeneration_ - if an error is detected inside hooked-component (could be detected during hot-renderer, if it is enabled) - react-hot-loader will fail the comparison between the old and the new component, causing remount.

"remount", and "reset" are proven fixtures :trollface:

**Comment by yoution** [comment] 2019-03-20 23:48
@theKashey  in my way, I  use  **babel-plugin-react-transform** other then **react-hot-loader** for hmr, but **babel-plugin-react-transform** does not support babel7, so I use **metro-babel7-plugin-react-transform** which is used by react-native hrm;as for forwarding refs, if you use refs in hook component, that may make no difference , if you want to use hooks from parent components, maybe I should use **React.forwardRef** in component which wrapping the hooks

**Comment by yoution** [comment] 2019-03-20 23:51
@natew  in my project , it works well, what do you mean?

**Comment by theKashey** [comment] 2019-03-21 00:15
`React.forwardRef` exists cos there is no other way to _forward a ref_. You will have to wrap your class with a `forwardRef`, to pass ref and another prop, to pass it down to the "real" component as a `ref` again. That would work, but does not sound good.

**Comment by h0jeZvgoxFepBQ2C** [comment] 2020-03-03 10:56
Any updates on this?

**Comment by theKashey** [comment] 2020-03-03 19:58
@h0jeZvgoxFepBQ2C:
- Hooks are expected to work
- RHL is in the deprecation mode
- Please try React Fast Refresh in case of any 🤷‍♂️

**Closed by theKashey** 2020-03-03 19:58 UTC
Labels: bug, discussion
