### ISSUE TITLE
beta.20 bug

### ISSUE THREAD

**Issue by fwh1990** [gaearon/react-hot-loader#841] opened 2018-02-05 03:23 UTC
Beta.20 cause rendering `only element` "012" in the browser.
```js
ReactDom.render(
  <App />,
  document.getElementById('root')
);
```
```html
<body>
  <div id="root">012</div>
</body>
```

node 9.5.0
babel 7.0.0.beta39
webpack 3.10.0

Rollback to beta.19 worked!

**Comment by theKashey** [comment] 2018-02-05 05:06
Unable to reproduce - all the tests I have are working.
Could you please provide a bit more code?

**Comment by fwh1990** [comment] 2018-02-05 05:35
Open chrome devTools, switch to `Elements`

```html
<div id="root">
  "0"
  "1"
  "2"
</div>
```

I just realize my root-component `AppComponent.render` method like:

```js
render() {
   return [
     <A key="axxx" />,
     <B key="bxxx" />,
     <C key="cxxx" />,
  ];
}
```

Return elements[] is legal in React16+

Any relation?

**Comment by fwh1990** [comment] 2018-02-05 05:37
```js
ReactDOM.render(
  <Provider store={store}>
    <AppComponent />
  </Provider>,
  document.getElementById('root')
);
```

**Comment by fwh1990** [comment] 2018-02-05 05:44
When I reduce array to 2 items, the render message turn to:
```html
<div id="root">
  "0"
  "1"
</div>
```

**Comment by theKashey** [comment] 2018-02-05 07:07
And there is no exception in console?

**Comment by theKashey** [comment] 2018-02-05 07:10
I've found a problem :(

**Comment by neoziro** [comment] 2018-02-05 08:24
Should be fixed in beta.21.

**Closed** 2018-02-05 08:24 UTC
Labels: bug, v4
