### ISSUE TITLE
bug in beta.21

### ISSUE THREAD

**Issue by fwh1990** [gaearon/react-hot-loader#843] opened 2018-02-05 16:18 UTC
```
Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
```

webpack 3.10.0
babel 7.0-beta39

Rollback to beta-19 worked.
I don't know why it happened, no more code provide to you, sorry.

**Comment by neoziro** [comment] 2018-02-05 17:21
This is our number one bug. @theKashey it seems to be introduced by your render PR.

**Comment by theKashey** [comment] 2018-02-05 21:02
@fwh1990 - so, as long you got a bug - you are the best person to track it down! 🏹 

1. Enable debug mode. setConfig({debug: true}). Maybe it will shed some light (probably not). 
2. Double check that this warning is just a warning. Ie react-hot-loader working correctly.
3. And what is you actually changing. Why something got unmount?

The problem is caused by #806. On each render, and pre-prender call each Component you use will compare some magical number. It will change when you execute a new portion of code (HRM, async-chunk, whatever).
Then, it thinks: hm, maybe it was HRM, lets double check.. and perform `hotReplacementRender`. And next it schedules a force update to all components updated. React will throw a warning if I do it during the render.

The question - why something got rendered, but next got unmounted.

So - what I am asking about - just double check that your application and RHL is working. 
If **yes** - I will just track the mounted state, and don't update freshly unmounted components.
If **no** - so that will a be a problem, as long it should be ok.

**Comment by skipjack** [comment] 2018-02-06 16:18
@theKashey I'm experiencing this issue too, it's being thrown on a ton of components. I don't fully understand all your points though...

> Enable debug mode. setConfig({debug: true}). Maybe it will shed some light (probably not).

I understand this point based on [this](https://github.com/gaearon/react-hot-loader/tree/next#switch-into-debug-mode).

> Double check that this warning is just a warning. Ie react-hot-loader working correctly.

As far as I could tell the loader still worked fine from a functionality standpoint, however maybe I'm missing something about this question.

> And what is you actually changing. Why something got unmount?

I'm not sure what you mean by this, but...

- One of the components with children in the tree unmounts.
- A varied amount of errors are thrown for components that don't contain any `setState`, `replaceState`, or `forceUpdate` calls.

Hope this helps. Not sure how much else I can dig into this but if needed I might be able to supply a reproducible example. Reverting to `4.0.0-beta.19`, as mentioned by @fwh1990, does fix the issue.

**Comment by theKashey** [comment] 2018-02-06 20:52
* One of the components with children in the tree unmounts.
> Is it expected behaviour? Something is unmounting cos it should do it, or it is a bug?

* A varied amount of errors are thrown for components that don't contain any setState, replaceState, or forceUpdate calls.
> RHL converts __all__ the components into the Stateful components, and also call `.forceUpdate` on them. So - you can have stateful error on stateless component 😸

**Comment by skipjack** [comment] 2018-02-06 21:00
> Is it expected behaviour? Something is unmounting cos it should do it, or it is a bug?

Yes, the unmounting is expected. Occurs when changing routes via `react-router`.

> RHL converts all the components into the Stateful components, and also call .forceUpdate on them. So - you can have stateful error on stateless component.

Yeah that would explain it. That sounds more like a "this package" issue rather than something a consumer of the package is doing wrong.

**Comment by theKashey** [comment] 2018-02-06 21:12
Ok. So everything is OK, and we should just track the component state to suppress the warning.

**Comment by fwh1990** [comment] 2018-02-08 03:48
Today, I look the exception again, and I think I have get the point.
You may try to test `react-loadable` package, the `loading component` make the problem.

```js
options = {
   loading: XxxComponent
}
```

```
warning.js:33 Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the XxxComponent component.
```

**Comment by fwh1990** [comment] 2018-02-08 03:55
You may try to test `react-loadable` package.

**Comment by fnpen** [comment] 2018-02-08 10:00
> You may try to test react-loadable package.

Have the same problem.

**Comment by fnpen** [comment] 2018-02-08 10:23
I'm using react-loadable@5.3.1

react-hot-loader@4.0.0-**beta.19** is working nice.

If react-hot-loader@4.0.0-**beta.21**:
`
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the loading component.
`
If react-hot-loader@4.0.0-**beta.20**:
`invariant.js:42 Uncaught Error: HotExportedApp(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

**Comment by theKashey** [comment] 2018-02-08 10:28
@fnpen the second error is a different error. And look it is __IS__ an error. Please provide more information.

**Comment by fnpen** [comment] 2018-02-08 10:49
@theKashey I can make repo with code to help reproduce it. Do you need it?

**Comment by theKashey** [comment] 2018-02-08 10:49
@fnpen - it will be just perfect.

**Comment by fnpen** [comment] 2018-02-08 11:48
@theKashey https://github.com/fnpen/react-hot-loader-mount-bug

Not working with clean create-react-app + react-hot-loader@4.0.0-beta.21.

Run `yarn start` and press button.

**Comment by theKashey** [comment] 2018-02-08 12:08
🚀

**Comment by fnpen** [comment] 2018-02-08 12:09
@theKashey @thibautRe

https://github.com/gaearon/react-hot-loader/blob/dd24b52a6d1c52210ca919a548d05764df7cdff1/src/AppContainer.dev.js 
```
shouldComponentUpdate(prevProps, prevState) {
    // Don't update the component if the state had an error and still has one.
    // This allows to break an infinite loop of error -> render -> error -> render
    // https://github.com/gaearon/react-hot-loader/issues/696
    if (prevState.error && this.state.error) {
      return false
    }

    return true
  }
```

Always true? Or need check original shouldComponentUpdate?

**Comment by theKashey** [comment] 2018-02-08 12:53
Always true. AppContainer shall not decide how the application would work.

**Comment by neoziro** [comment] 2018-02-10 20:17
Fixed in beta 22.

**Closed by neoziro** 2018-02-10 20:17 UTC
Labels: bug, v4

**Comment by fnpen** [comment] 2018-02-10 21:25
@neoziro @theKashey  thanks!

**Comment by fnpen** [comment] 2018-02-11 08:15
@theKashey solved for example. But error exists in my app with redux / react-router. I will try extract the reason to my example.

**Comment by theKashey** [comment] 2018-02-11 09:30
@fnpen - just share some sources.

**Comment by FallOutChonny** [comment] 2018-02-12 03:58
Hello, first of all I would like to thank you guys for maintaining this project.
I update RHL to 4.0.0-beta.22 and have similar problem, project used:

`react` - 16.2.0 with SSR
`styled-components` - 3.1.6
`react-loadable` - 5.3.1
`babel` - 7.0.0-beta.38
`webpack` - 3.10.0

When I edit file and save changes, terminal shows
![Imgur](https://i.imgur.com/6EMEAk2.png)

and developer tools shows
![Imgur](https://i.imgur.com/eDP8St8.png)

Or I don't edit file, just change the route, developer tools shows a lot of warning messages
![Imgur](https://i.imgur.com/LdgSGEF.png)

Hot-reload is ok, but the warning message looks a bit annoying.
Could you please help me? Thank you.

**Comment by theKashey** [comment] 2018-02-12 06:01
HotExportedAbout should synchronously flush the changes, but it doesn't do it. Just a few lines to debug.

**Comment by theKashey** [comment] 2018-02-13 07:38
I've failed to find the reason about "Can only update" - should be ok in last beta, in case you dont get error with "cannot read children".
And that error is actually an error - https://github.com/gaearon/react-hot-loader/pull/830#issuecomment-365127831, fixing it right now.

**Comment by cyrilwanner** [comment] 2018-02-13 12:59
I also have the same issue in beta.22 ("Can only update" but without the children error FallOutChonny has). React-hot-loader still works as expected, there are just these additional warnings.

I've setup an example project with `loadable-components` as I also have this in my real project, if it helps you debugging the cause: https://github.com/cyrilwanner/react-hot-loader-bug (follow the steps in the readme to reproduce the bug)

**Comment by theKashey** [comment] 2018-02-13 20:40
@cyrilwanner - thank you. Looking....

**Comment by theKashey** [comment] 2018-02-13 21:46
Ok, kudos to @cyrilwanner, not it's clear - HRM/RHL works very well. A bit more very than it should.

1. You are updating *something*. Everything is ok, and update got `scoped` by __hot__ HOC.
2. Meanwhile global variable, we call _generation_ got increased.
3. When you hit a button, and change route - whole React tree star re-rendering.
4. "Sub-render" trap detect that something gonna to be rendered, but that something was rendered within lower _generation_, and may contain async-updated HRM chunks.
5. It starts hot-render process, which do it's work just great.
6. Meanwhile, hot-render just rendered the old react tree, cos __react-hot-renderer ignores context changes__, as long they are outside just __rendering__ it could(and shall) perform.
7. Now it is a time for a normal React rendered. It renders tree as it should be, and unmounts components scheduled for update.
8. Profit 👍 

The ways to fix:
1. The logic in .4 is just incorrect. It should react only to react updates occurred just after HRM event, the renders normal flow might just miss(portals, async-loaded components and so on).
Have no idea how to distinguish these two execution branches -_ just after_ HRM, and _10 seconds_ after HRM. Or how to "raise" stored generations of all the components, not related to a specific update.
2. Try to hook into `willRecieveProps`. That will allow just sync-flush of force-updates.
3. Track the mounted state of components, just to hide these errors.

WIP.

**Comment by theKashey** [comment] 2018-02-14 06:46
2 and 3 implimented.
