### ISSUE TITLE
React component state gets lost when jsx tag below gets removed

### ISSUE THREAD

**Issue by hoschi** [gaearon/react-hot-loader#546] opened 2017-04-12 08:14 UTC
### Description

React component state gets lost when jsx tag below gets removed, when one above gets removed it works fine.

Steps:
* fetch demo repo: https://github.com/hoschi/bare-minimum-react-hot-rr4-redux/tree/loosing-state
* start dev server and open site in browser: http://localhost:8080/page3
* use spinner to change number to e.g. 6, which is saved in component state of Page1

### Expected behavior

* remove ['above'](https://github.com/hoschi/bare-minimum-react-hot-rr4-redux/blob/559a9bfce52d97fa48a314f404e8255f74ec81d5/src/components/Page3.jsx#L8 ): value of in put should be still '6'
* remove ['below'](https://github.com/hoschi/bare-minimum-react-hot-rr4-redux/blob/559a9bfce52d97fa48a314f404e8255f74ec81d5/src/components/Page3.jsx#L10 ): value of in put should be still '6'

### Actual behavior

* remove ['above'](https://github.com/hoschi/bare-minimum-react-hot-rr4-redux/blob/559a9bfce52d97fa48a314f404e8255f74ec81d5/src/components/Page3.jsx#L8 ): value of in put is still '6' (works)
* remove ['below'](https://github.com/hoschi/bare-minimum-react-hot-rr4-redux/blob/559a9bfce52d97fa48a314f404e8255f74ec81d5/src/components/Page3.jsx#L10 ): value of in put is '1' (doesn't work)

### Environment

React Hot Loader version: 3.0.0-beta.6
https://github.com/hoschi/bare-minimum-react-hot-rr4-redux/blob/559a9bfce52d97fa48a314f404e8255f74ec81d5/package.json#L19

Run these commands in the project folder and fill in their results:

1. `node -v`: 6.3.1
2. `npm -v`: 3.10.3

Then, specify:

1. Operating system: Linux (Arch)
2. Browser and version: Chrome, 56.0.2924.87 (64-bit)

### Reproducible Demo

https://github.com/hoschi/bare-minimum-react-hot-rr4-redux/tree/loosing-state

**Comment by neoziro** [comment] 2017-12-25 13:58
Working on it.

**Comment by neoziro** [comment] 2017-12-26 18:14
@theKashey https://github.com/neoziro/bare-minimum-react-hot-rr4-redux/tree/loosing-state this looks weird, state is lost.

**Comment by theKashey** [comment] 2017-12-26 23:53
Above..
There is 2 issues with code itself:
1. Page1 starts timers on construction, but should on mount.
2. by the time page1-3 were executed react-hot-loader is NOT (in RootApp).

This is a quite important moment, and we should point on it in readme, and maybe add some reporting via babel plugin.
__ you have to import react-hot-loader before any other component __ Or REACT_HOT_LOADER variable, all components will `register` into will not exists.
By fact - on the first change you will got all components remounted, cost they all were `auto`-wrapped before, and now they are registered ones.

There is also an issue with React itself:
<img width="483" alt="screen shot 2017-12-27 at 10 38 51 am" src="https://user-images.githubusercontent.com/582410/34366676-639a4054-eaf3-11e7-942c-7e5ad6504007.png">
As long prev and next elements are completely different - it will unmount/mount all the things.

To make it work one has to add `keys` to rendered elements, letting React know that's happening.

```js
<p key="above">above, remove this and Page1 looses statrkke</p>
<Page1 key="page"/>
<p key="below">below, remove this and Page1 keeps state</p>
```

Result: there is nothing to be fixed in RHL, but there is one moment to improve.

**Comment by neoziro** [comment] 2017-12-27 09:35
@theKashey 

- I tried to use keys and it didn't solve it
- Timer was just a test, I clean it up using didMount / willUnmout but it is not the point
- So for you this is "normal" and we should just mention it in README?

**Comment by neoziro** [comment] 2017-12-27 15:17
OK I retried it with last version, two problems:

- Removing "above" cause a unmount / mount, this is React behaviour, using key no problem
- Hot Reloading does not work the first time, and we can fix it

Instead of ignoring it if `__REACT_HOT_LOADER__` is not present we could create a `__REACT_HOT_LOADER__` temp in Babel and replace it by the true one when `patch.js` is loaded. This is exactly the strategy of Google Analytics with global `ga`.

https://github.com/gaearon/react-hot-loader/blob/41520935adcf655aab033b28e1c660f62be494ae/packages/react-hot-loader/src/babel.js#L30-L40

@theKashey what do you think? I think it is better than including `patch.js` by ourself because we do not know where we are with Babel.

**Comment by neoziro** [comment] 2017-12-27 15:33
Described this in a separated issue #738.

**Comment by hoschi** [comment] 2017-12-29 08:26
> Removing "above" cause a unmount / mount, this is React behaviour, using key no problem

You mean that bug is expected behaviour, because there are two `p` tags without keys?

**Comment by neoziro** [comment] 2017-12-29 09:07
This is not a bug, this is exactly the behaviour of React, React uses index as key by default to changing the order triggers a unmount / mount.

**Closed** 2018-02-27 10:08 UTC
Labels: bug, fixed in next
