### ISSUE TITLE
Cannot resolve module 'react/lib/ReactMount'

### ISSUE THREAD

**Issue by coderwin** [gaearon/react-hot-loader#421] opened 2016-11-18 03:53 UTC
React 15.4.0:

react/lib/* => react-dom

**Comment by maxilev** [comment] 2016-11-18 14:18
+1

**Comment by calesce** [comment] 2016-11-18 14:34
Duplicate of #417. we'll get the fix out tonight/tomorrow, but probably stop updating 1.X after that.

**Closed by calesce** 2016-11-18 14:34 UTC
