### ISSUE TITLE
Checking Element types workaround doesn't cover children prop :(

### ISSUE THREAD

**Issue by alexey-kachalov** [gaearon/react-hot-loader#710] opened 2017-12-06 07:45 UTC
### Description
Our solution needs to check types of elements. It is needed for building complex component tree by "meta components".
There is a known issue with the `react-hot-loader`, described here: https://github.com/gaearon/react-hot-loader#checking-element-types

Described workaround
```
const ComponentType = (<Component />).type;
const element = <Component />;
console.log(element.type === ComponentType); // true
```
works, but there is the problem with children prop there.

### Expected
We need to figure out how to remove warnings of required children, when we use above described workaround.

### Actual behavior
There are warnings in a browser console about required children if we use proposed workaround.

**Comment by theKashey** [comment] 2017-12-06 09:45
Got the point. There is no way to help you now, but in the future you might get 2 solutions.
1. Is to use instanceOf, not type equality check
```js
const element = <Component />;
console.log(element.type instanceOf Component); // true (currently - false)
```
2. We could expose a helper function for type comparison.
```js
console.log(areComponentsEqual(element.type,Component)); // true
```
We also had this function internally.

PS: This is a duplicate of #304, and you might find few tips and tricks inside. Which will not help in your case, sorry.

**Comment by alexey-kachalov** [comment] 2017-12-06 09:53
@theKashey , thank you. I would like personally to have the helper. But it should work also without `react-hot-loader` in production I think.

**Closed** 2017-12-06 22:32 UTC

**Comment by alexey-kachalov** [comment] 2017-12-06 22:33
Closed due to duplication. See the continuation here: https://github.com/gaearon/react-hot-loader/issues/304#issuecomment-349613396
