### ISSUE TITLE
[v4] Page reloads every second component change (Redux connected)

### ISSUE THREAD

**Issue by rusty3** [gaearon/react-hot-loader#820] opened 2018-01-25 10:54 UTC
### Description

This issue is happening on a bare setup with latest React Hot Loader V4 when updating Redux connected component.

### Expected behaviour

Component should be updated without page reload.

### Actual behaviour

Component is hot updated on the FIRST change, however every second change the following errors happen and the page is reloaded.

[HMR] Cannot apply update. Need to do a full reload!
[HMR] Error: Aborted because ./src/ConnectedContainer.js is not accepted
...
### Environment

React Hot Loader version: v4 (latest beta 17)
node v8.9.1
npm 5.6.0
OS: macOS Sierra 10.12.6
Browser: Chrome Version 63.0.3239.132 (Official Build) (64-bit)

### Reproducible Demo
https://github.com/rusty3/react-hot-loader-redux-connect-issue

**Comment by theKashey** [comment] 2018-01-25 11:59
@rusty3, you made my day.
We have introduced cyclic dependency in our code, and everything is broken.

**Comment by neoziro** [comment] 2018-01-25 13:41
Fixed in 4.0.0-beta.18.

**Closed by neoziro** 2018-01-25 13:41 UTC
Labels: WIP, bug, v4

**Comment by eXaminator** [comment] 2018-06-14 08:50
Was this error somehow reintroduced? I'm seeing this exact behaviour and error with 4.3.2. All I did was exactly what is documented in the readme. It's a big application with a small (lazy loaded) react part, so it might be something in my general setup. But it is strange that it works on the first change but mot the second.

**Comment by theKashey** [comment] 2018-06-14 11:36
@eXaminator - any error in console, especially with `setConfig({logLevel:'debug'})`?

**Comment by meds** [comment] 2018-06-15 07:20
@eXaminator I am having the problem too! My app is much more simple, I followed the documentation and every second component change I get a fullscreen reload..

**Comment by eXaminator** [comment] 2018-06-15 16:52
I'm on a trip right now, so I'll check once I'm back at work in about a
week!

meds <notifications@github.com> schrieb am Fr., 15. Juni 2018, 08:21:

**Comment by meds** [comment] 2018-06-16 10:31
I found the cause of the problem in my case, in app.tsx I was initializing firebase in the global scope. When I moved it into 'onComponentDidMount()' my issue was resolved.

**Comment by njgraf512** [comment] 2018-08-26 04:32
Having the same problem. Any suggestions would definitely be appreciated.

**Comment by theKashey** [comment] 2018-08-26 11:26
@njgraf512 -using the latest version?
