### ISSUE TITLE
Hot reloading breaks if component is not in it's own file

### ISSUE THREAD

**Issue by Cottin** [gaearon/react-hot-loader#163] opened 2015-07-15 15:30 UTC
I tried using "render callbacks" as props which did not hot-reload. Then I switched to "function as children" which did not get hot-reloaded either. I'm guessing that is what's covered in #145 or am I miss reading that?

I thought I'd give one last try to implement this "render callback" pattern by specifying the type of component in a prop instead, and declaring that component type in the same file. (Not a perfect solution but ok). However this does not seem to get hot-reloaded either. Is there any way of achieving what I'm trying to achieve here?

e.g.:

Does *not* get hot-reloaded:

````
# MyComponent.coffee
MyComponent = React.createClass
  render: ->
    div {},
      this.props.childComponentType {a: 'hello', b: 'world'}

# AppView.coffee
MyChild = React.createFactory React.createClass
  render: ->
    div {}, this.props.a + ' ' this.props.b

AppView = React.createClass
  render: ->
    MyComponent {childComponentType: MyChild}
````

If I split  MyComponent into a separate file, hot-reloading works again:

````
# MyComponent.coffee
MyComponent = React.createClass
  propTypes:
    childComponentType: React.PropTypes.object
  render: ->
    div {},
      this.props.childComponentType {a: 'hello', b: 'world'}

# MyChild.coffee    <------- split it out into a separate file
MyChild = React.createClass
  render: ->
    div {}, this.props.a + ' ' this.props.b

# AppView.coffee
MyChild = React.createFactory require './MyChild'
AppView = React.createClass
  render: ->
    MyComponent {childComponentType: MyChild}
````

**Comment by gaearon** [comment] 2015-07-15 22:23
React Hot Loader requires you to put every component into a separate file and export it.
Does this help?

**Comment by gaearon** [comment] 2015-08-22 21:13
Closing because this is by design.
We'll have a way to avoid it later, but it will be available as a Babel plugin that will make RHL obsolete.

**Closed by gaearon** 2015-08-22 21:13 UTC
