### ISSUE TITLE
Code change was recognized but Nothing hot updated

### ISSUE THREAD

**Issue by hieuhlc** [gaearon/react-hot-loader#343] opened 2016-08-16 07:17 UTC
I followed the instruction in http://gaearon.github.io/react-hot-loader/getstarted/
And got `Hot Module Replacement enabled` but when i changed my code, it can not be hot updated.

<img width="321" alt="screen shot 2016-08-16 at 14 10 11" src="https://cloud.githubusercontent.com/assets/4828178/17690941/0f671454-63bc-11e6-9c71-0b3d572756d0.png">

How can i get this to hot reload?

**Comment by tsaiDavid** [comment] 2016-09-03 00:32
@hieuhlc @gaearon - I'm facing the same issue myself in a larger app. Could you please share which versions (`react-hot-loader` & `webpack`) you're using? Are you running into this issue using RHL3?

**Comment by hieuhlc** [comment] 2016-09-03 03:40
@tsaiDavid I used `react-hot-loader 1.3.0` and `webpack ^1.9.11`. I haven't tried RHL3.

**Comment by calesce** [comment] 2016-09-07 01:18
@hieuhlc any way you can create a repo that reproduces the issue?

**Comment by calesce** [comment] 2016-10-09 18:37
Closing because you didn't respond, but please re-open if you're still having problems!

**Closed by calesce** 2016-10-09 18:37 UTC
Labels: unconfirmed

**Comment by sandor11** [comment] 2017-03-08 13:56
@calesce Hi, I have a similar issue. I have created a repo with the bare minimum. I have setup [https://bitbucket.org/sandoz_dev/react-hmr-boilerplate.git](url)

The `master` branch, works pretty well, but **HMR** still can be intermittent. I have also created a branch `with-sass-loader` where the, _update recognized -> changes not reflected_ problem is pretty much constant.

One thing I noticed, is in the dev tools, new style sheets are appearing in the sources tab under the  `webpack:// > . > components` folder, but the `<style>` tags are only sometimes replaced. 

Other environment stuff
- Windows 10
- Node 7.5.0

Any help would be appreciated. It is so close to being perfect, **HMR** will be a great step forward for my workflow. 

If you need any further info, just let me know.

**Comment by sandor11** [comment] 2017-03-20 12:43
To follow up...

I have just found out it was an issue with my IDE (WebStorm) as referenced here https://webpack.github.io/docs/troubleshooting.html#file-saves-in-webstorm-don-t-trigger-the-watcher

Everything is work as expected using the code from my previous comment.

**Comment by robbporto** [comment] 2018-03-19 20:23
Similar problem here. When I edit the parent component, everything works fine. When I edit the child component, the code doesn't compiles.
