### ISSUE TITLE
Get it working with SystemJS

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-loader#275] opened 2016-05-02 01:43 UTC
https://github.com/alexisvincent/systems-hmr/issues/1

**Comment by tyscorp** [comment] 2016-05-02 02:11
I can confirm that react-hot-loader does indeed work the same for jspm as it does webpack.

[Working example repo](https://github.com/tyscorp/react-hot-boilerplate/tree/jspm)

As far as I can see, the state is reset under the same circumstances that it resets while using webpack.

For example, inserting a new node above [this line](https://github.com/tyscorp/react-hot-boilerplate/blob/jspm/src/Layout.js#L7) causes a state reset for both jspm and webpack, whereas changing the JSX below that line works fine for both.

**Comment by alexisvincent** [comment] 2016-05-02 14:55
@tyscorp @gaearon I think the issue is actually with react router.

**Comment by gaearon** [comment] 2016-05-02 15:22
Can you give `beta.1` a try? It uses a different approach (#272). I haven’t had a chance to look at this yet but I might find some time in a week or two.

**Comment by alexisvincent** [comment] 2016-05-02 15:25
@gaearon Figured out a way to reproduce.

This works
```js
    ReactDOM.render(
      <AppContainer><App /></AppContainer>,
      rootEl
    );
```

this fails
```js
    ReactDOM.render(
      createElement(AppContainer, null, 
           createElement(App),
      rootEl
    );
```

**Comment by alexisvincent** [comment] 2016-05-02 15:26
@gaearon I wonder if it isn't because Im using createElement which I import from react. This should be overwritten shouldn't it?

**Comment by gaearon** [comment] 2016-05-02 15:50
>I wonder if it isn't because Im using createElement which I import from react. This should be overwritten shouldn't it?

As long as `react-hot-loader/patch` runs before any other imports.

**Comment by gaearon** [comment] 2016-05-02 17:28
Might be caused by this: https://github.com/gaearon/react-hot-loader/issues/276#issuecomment-216302815.

**Comment by alexisvincent** [comment] 2016-05-02 17:30
@gaearon Yeah Looks about right

**Comment by gaearon** [comment] 2016-05-02 17:37
Hmm. But no, you are using `createElement`, not a factory. I’ll need to look at it later but I think that in your case `react-hot-loader/patch` executes later than it should.

**Comment by alexisvincent** [comment] 2016-05-02 17:50
Hmm. Ill force it to load well before to test... Also, I've never used JSX but I thought it was a source transform... How does it get access to ```createElement```

**Comment by alexisvincent** [comment] 2016-05-02 17:56
@gaearon I loaded ```react-hot-loader/patch``` in a promise and on completion loaded the rest. Same issue. I wonder if theres an issue with multiple versions of react?

**Comment by alexisvincent** [comment] 2016-05-02 17:57
@gaearon Nope. Only one version of react is being loaded

**Comment by gaearon** [comment] 2016-05-02 18:02
Yeah, hard to guess. I’ll need to look into this when I get some time.

**Comment by calesce** [comment] 2016-10-23 15:26
@alexisvincent Hey, I was taking a look at this and unable to install via your repo's instructions. On `jspm install` (with jspm beta.29), I got:
`err  Error looking up npm:@alexkuz/react-json-tree.`
I tried again and got 
`err  Error parsing package.json file /Users/calenewman/code/jspmloader/systemjs-react-hot-reloader/jspm_packages/npm/domain-browser@1.1.7.json`

**Comment by alexisvincent** [comment] 2016-10-24 19:40
Hi @calesce, I'm glad you replied because a few days ago I hit this issue again but had forgotten about this issue. Was going to create another. I'll get a project up for you to reproduce within the hour. Going to just see if it's the same issue.

**Comment by alexisvincent** [comment] 2016-10-24 22:44
@calesce New repo code is up. Vastly simplified. Everything should work. Basically it seams that the issue is when using createElement instead of JSX.

**Comment by alexisvincent** [comment] 2016-10-24 22:46
Hmm. I think i forgot AppContainer in this version. Weird that it works and doesnt even without the container. Will add it now and see if this resolves the issue

**Comment by alexisvincent** [comment] 2016-10-24 23:24
Done, same issue

**Comment by calesce** [comment] 2016-10-25 00:54
OK, yeah I reproduced your issue. 

Also, even with JSX, on the first edit after reloading the page, it is slow to update and unmounts the component. All edits after that are fast, and the component isn't re-mounted.

@tyscorp's project had the same issue with `createElement`, but it didn't have the problem with the first edit. It might be a difference between `systemjs-hot-reloader` and `jspm-devtools` (I'm not familiar with the JSPM ecosystem :D).

**Comment by alexisvincent** [comment] 2016-10-25 07:50
@calesce yeah I still need to sort that out. It has to do with how jspm-devtools bundles files initially. Will be fixed as soon as I start pushing dependencies over http2 server push

**Comment by alexisvincent** [comment] 2016-10-25 07:50
But glad you were able to reproduce.

**Comment by alexisvincent** [comment] 2016-11-04 20:26
@calesce Any progress on this?

**Comment by calesce** [comment] 2016-11-04 20:34
@alexisvincent sorry no, not yet. When I get some extended time to look, I'll probably double check that the createElement being used is the [patched version](https://github.com/gaearon/react-hot-loader/blob/2ce0b3c27520777ae78b6050efbf5891577fb4c8/src/patch.dev.js#L153). I don't have any other leads beyond that.

**Comment by alexisvincent** [comment] 2016-11-04 22:08
I can confirm that upon a reload, react proxy is running an update. Don't know what that means for createElement. It seems that react proxy isn't keeping the state

**Comment by neoziro** [comment] 2017-09-19 20:11
This issue seems outdated, I close it, feel free to add a comment if you experienced a problem relative to jspm.

**Closed by neoziro** 2017-09-19 20:11 UTC
Labels: help wanted, unconfirmed
