### ISSUE TITLE
Element type comparing

### ISSUE THREAD

**Issue by Mistereo** [gaearon/react-hot-loader#304] opened 2016-05-29 17:18 UTC
It seems like with react-hot-loader@3 it's not possible to check element type for imported components:

``` javascript
const element = <ImportedComponent />
console.log(element.type === ImportedComponent)
```

Logs `false` for me.
Is this a bug or something that should not be supported?

**Comment by nfcampos** [comment] 2016-06-02 08:02
Hi @Mistereo 

This is intended, react-hot-loader@3 patches `React.createElement`(`<ImportedComponent />` is equivalent to `React.createElement(ImportedComponent)`) so that it returns an element of a proxy wrapper for your components instead of the original component, this is part of allows to replace methods on the component without unmounting.

Do you have any need for `<ImportedComponent />.type === ImportedComponent` to be true?

**Comment by Mistereo** [comment] 2016-06-02 09:27
@nfcampos I'm trying to implement conditional rendering depending on children types.
I can just set some static prop on these components as a workaround, and check this prop instead.
Just wondering if this can be avoided.

**Comment by nfcampos** [comment] 2016-06-03 19:40
@Mistereo no, I don't think it can be avoided with the current architecture

**Comment by JorgenEvens** [comment] 2016-06-09 20:55
I'm running into the same problem, this is how I am working around the issue:

```javascript
const ImportedComponent = (props) => { ... }
const ImportedComponentType = (<ImportedComponentType).type;

const element = <ImportedComponent />
console.log(element.type === ImportedComponentType)
```

**Comment by singggum3b** [comment] 2016-06-15 04:13
this is definitely a big flaw ! not able to check child type of which class ...

**Comment by w3apps** [comment] 2016-06-15 06:41
Is it possible to fix this thing or is it too big of a change?

**Comment by harmony7** [comment] 2016-07-14 05:59
Ran into this today.

One option is to check using `.type.name` like this:

```
import Component from /* ... */;
// Check like this
element.type.name === Component.name
```

However, even this would also break once the resulting code was minified.

So for now I'm using @JorgenEvens 's workaround, thanks for that.

**Comment by c58** [comment] 2016-08-01 08:18
I used another approach...
```
const ImportedComponent = (props) => { ... }
ImportedComponent.isMyImportedComponent = true;

// Check like this
element.type.isMyImportedComponent === true
```

**Comment by phyllisstein** [comment] 2017-02-06 11:28
Just ran into this myself and I'm pretty stumped. I'd love to do something a little more elegant than checking `displayName` or cramming my components with static flags, but I can't seem to figure out a solution. Is it really hopeless, @nfcampos ?

**Comment by Soweyln** [comment] 2017-10-05 17:06
@gaearon Just want to check beforehand that is it **possible** to fix this in a systematical way or not? If yes, I'll try to dig into it and fix. Thanks.

**Comment by elado** [comment] 2017-10-11 22:26
also posted on react-proxy https://github.com/gaearon/react-proxy/issues/80

**Comment by Lohann** [comment] 2017-10-22 19:10
+1

**Comment by lgra** [comment] 2017-11-06 18:34
Based on what's said here, I've build a very little Babel plugin which transforms `foo.type === MyComponent` in `foo.type === (<MyComponent />).type`.

Save it as a .js file and reference it in your babel options in dev mode.

```
module.exports = function (babel) {
  var t = babel.types;
  return {
    visitor: {
      BinaryExpression(path) {
        if (
          (path.node.operator === '===')
          && (t.isMemberExpression(path.node.left))
          && (t.isIdentifier(path.node.left.property))
          && (path.node.left.property.name === 'type')
          && (t.isIdentifier(path.node.right))
        ) {
          var className = t.stringLiteral(path.node.right.name).value
          var newExpr = t.memberExpression(t.jSXElement(t.jSXOpeningElement(t.jSXIdentifier(className), [], true), null, [], true), t.identifier('type'))
          var rightPath = path.get('right')
          rightPath.replaceWith(newExpr)
        }
      }
    }
  }
}

```

**Comment by theKashey** [comment] 2017-11-06 21:56
@lgra - it will not always work, and even can break some generic code. The problem is that React-Hot-Loader will always `somehow` wrap original class with `something` to.. just do his work.
And that `somehow` is the internals you should not rely on. It might be changed at any point.

Currently, there are 4 options:
 1. Trick by @JorgenEvens. It will always work.
 2. We can ask react-proxy to expose the original class as @yesmeck propose in https://github.com/gaearon/react-proxy/issues/68
 3. It is possible to make construction ```element.type instanceOf ImportedComponent``` work. Will you use it?
 4. We can wrap the original class just after creation, so comparisons will start working instantly. But it will introduce yet another magic code transform we are trying to avoid.

The best way, I can imagine - we can expose special function for comparison, but how to provide a requirement to use it?

**Comment by lgra** [comment] 2017-11-06 23:11
@theKashey hi Anton. My point of vue is to be less intrusive as possible. At my company, several projects share dozen of UI components. Every projects are not using the same version of REACT, webpack, Babel or even ReactHotLoader. The type comparison is often used in our components, and I don’t want to modify this share code as I can’t quantify the risk, nor the impact on production code - where this modification is not necessary.
This is why I’ve created this Babel plugin. It doe’s the @JorgenEvens trick on the fly at transpiration time. I’m applying it only to my shunk, and only in dev mode.
This allow me to use latest version of ReactHotLoader, without any change in my code nor colegue code, and without any impact on production code.
I’m pretty sure you’re true when you say it won’t fit any situation. I don’t give this as an universal solution. It’s just an other way to implement the trick, that can save time in some circontances.

**Comment by theKashey** [comment] 2017-11-07 00:27
@Igra - can you show the rest of your babel plugin? To be more clear - `newExpr`.
Actually - code might be quite safe if
```js
element.type === ImportedComponent

// will be transpiled into

compareRHL(element.type, ImportedComponent);

//where
compareRHL = (a,B) =>{try{ return a===b || (typeof React !== 'undefined' && a===<B>.type)} catch(e){} return false; } 
```
Key points -> keep the old comparison, and there might be no React, and long something.type === something is quite generic.

**Comment by lgra** [comment] 2017-11-07 06:53
@theKashey - There's nothing else ! You've got here the whole code of the plugin. It doesn't produce final transpiled code. It produces JSX code that will be transformed by babel.

```
// Things like:
element.type === ImportedComponent

// is transform to
element.type === <ImportedComponent />.type
```

In the Abstract Syntax Tree, the plugin matchs strict egality expressions (`BinaryExpression` where `operator` is `===`), where left is the literal `type` property of any object (a `MemberExpression` where `property` is an `Identifier` of name `type`), and where right is an `Identifier` (assuming this identifier is a REACT class).
In the matched expression, it replaces the right path by the type member of an JSX element of the JSX identifier found as the right parts of the expression:

```
t.memberExpression( // an object member expression
  t.jSXElement( // the object is JSX element expression ...
    t.jSXOpeningElement( // ... where opening element ...
      t.jSXIdentifier(className), // ... is of class identified by the right parts of the egality - className = t.stringLiteral(path.node.right.name).value
      [], true // ... with no attributes nor closing element
    ),
    null, [], true // no children
  ),
  t.identifier('type') // the member is identified by the name 'type'
)

```

This is the same AST tree as if you write your code the @JorgenEvens way.

The limit of this plugin is that it's assuming that the right identifier is a REACT class identifier. If you don't use `type` for something else than REACT object instance type, this is not an issue. And event if you uses a custom `type` member for something else and want to compare it to something, invert the binary expression to make the plugin skip it.

**Comment by theKashey** [comment] 2017-11-07 22:55
But is far not easy to transpile something in node_modules and get all the things working properly. 
Anyway - sooner or later we will solve this.

**Comment by gaearon** [comment] 2017-11-08 00:12
No, transpiling node_modules is definitely **not** the way this should be solved (if it is solvable at all).

**Comment by theKashey** [comment] 2017-11-08 01:17
@gaearon - could React help? Expose an underlaying type from a proxy as .type prop?

In the same time I am just wondering - why one need this comparison outside the tests. What are you going to solve, to archive?

I mean - should the case be solved at all.

**Comment by lgra** [comment] 2017-11-08 07:08
@gaearon I've got rules in my Webpack config to apply it only to my own modules and git submodules - but you're true : what if a npm module need to be patch ? and for instance, I don't have any external npm modules presenting this pattern.

@theKashey We're using this pattern in some of our components.
Case 1: A father element will inject some specific logic to a child element if it's of a certain type. For example, a CustomRadioGroup element will compute a unique name and inject it to any CustomRadio child - but not to CustomLabel child.
Case 2: A father element will reflow its children depending on there kind. For example, CustomTable will have some CustomHeader, some CustomHeaderRow and some CustomRow children. CustomTable will render a HTML table tag, and put any CustomHeader in header tag, CustomHeaderRow in thead tag, and CustomRow in tbody. It could also parse the first CustomHeaderRow to generate colgroup and col tag accordingly.

@gaearon @theKashey Maybe it's not a good pattern. Maybe a specific static property of the class is a better way - it allows the definition of several classes that will behave the same way when put into a father (for example, CustomOddRow and CustomEvenRow are body rows - not so far than the concept of `display: table-row`). I'll think about a `behaviors` static array property.

**Comment by theKashey** [comment] 2017-11-08 11:54
Look like the best way to solve this issue (and not only this one) - it is move React-Hot-Loader from React, to React-dom. Solve it from inside.

As long all idea around RHL is to bypass Reconciler's ```element.type === existingChild.type```, and we are trying to undo this inside the client code.  Left arm is fighting with the right one.

Anyway - this task could be solved for ES5 classes, as long we have full access to the prototype and do all the magic we need, but I am not sure about ES6 as long `classed` are sealed a bit.

PS: @neoziro - still awaiting you on Trello board.

**Comment by lgra** [comment] 2017-11-13 11:12
@gaearon I agree with you. As long as a proxy is used, as type is a readonly property, and as it's used internally by REACT when cloning element, I'm pretty sure it's not solvable at all.

**Comment by theKashey** [comment] 2017-11-22 11:06
So - it task is close to `doable`.
It is possible(*) to always use the first instance of a class or a function.
 - in case of class we can monkey-patch the original prototype, and backport some changes via life cycle methods. As long constructor in es6 is immutable - it is the only way.
 - in case of stateless functional component, it is also "doable", but will require changes on the React side -> replace FunctionCall(params) by Function.call(null, params..). Next one can overload .call method of a function to hot-replace it.

So - it is doable, but I am not sure that one should try to solve this problem.

**Comment by neoziro** [comment] 2017-11-24 16:03
@theKashey tricky

**Comment by bathos** [comment] 2017-12-04 06:46
@lgra thanks very much — it may be brittle, but it’s better than adding nonsense code in prod — with a little adaptation this addresses it for me for now.

**Comment by alexey-kachalov** [comment] 2017-12-06 11:34
Maybe it would be worth to add a helper function which will do all the magic, based on the implementation of `react-hot-loader`?

Something like that:
```
import React from 'react';

export const isElementOfType = component => {

  // Trying to solve the problem with 'children: XXX.isRequired' (https://github.com/gaearon/react-hot-loader/issues/710). This is not work for me :(
  const originalPropTypes = component.propTypes;
  component.propTypes = undefined;
  
  // Well known workaround
  const elementType = (<Component />).type;

  // Restore originalPropTypes
  component.propTypes = originalPropTypes;

  return element => element.type === elementType;
};
```

**Comment by lgra** [comment] 2017-12-06 13:20
@bathos You're welcome.
I have enhanced my babel plugin to make replacement only if the right parts of the comparison is an imported class, and log what it had replace. Here's the code:
https://github.com/lgra/lg-webpack/blob/master/scripts/babel-type-comparison.js

**Comment by theKashey** [comment] 2017-12-06 13:23
```js
import {isComponentsEqual} from 'react-hot-loader'

isComponentsEqual(element.type, ImportedComponent);

// for production
const isComponentsEqual = (a, b) => a === b;

// for dev
const isComponentsEqual = (a, b) => a  === b || a === getProxyByType(b);
```
Some things is easier doable from inside.

**Comment by alexey-kachalov** [comment] 2017-12-06 13:37
@theKashey it is ok for my issue. =) It would be worth to add that to `react-hot-loader`.
P.S. I think you meant `areComponentsEqual` instead of `isComponentsEqual`.

**Comment by theKashey** [comment] 2017-12-06 13:56
It's a 0:55 on the clock. I am already not here a bit.

**Comment by alexey-kachalov** [comment] 2017-12-06 22:23
@theKashey , @gaearon can the function `resolveType` (https://github.com/gaearon/react-hot-loader/blob/master/src/patch.dev.js#L139) be exported as public API?

I would like to use it for type checking in the following manner (if I get it correctly, it should work):
```javascript
// Helper (for 'dev' environment):
const isElementOfType = type => element => resolveType(type) === element.type

// Usage:
const isFoo = isElementOfType(Foo)
const isFoo(<Foo />) // true
```
Are there reasons not to export the `resolveType` as public?

**Comment by theKashey** [comment] 2017-12-07 01:12
The main reason - your code should not relay on RHL internal implementation. But there is no way :(
What I could propose:
1. We are exporting resolveType, but you are __not__ using it
2. We could add @lgra's magic into our babel plugin, to `fix` the issue seamlessly for you.
3. Is automagicaly does nothing for production code.

You will not change your code, but your code will work. This is not a great solution, as long it will not fix third party libraries, which may relay on type, but this is far better that nothing.

**Comment by alexey-kachalov** [comment] 2017-12-07 04:51
I agree about 3rd parties. :( But it is not good for RHL as devtool to have such "unresolvable issues" as this one. In the case the devtool has a big influence to production. I think it is something like a problem. :/ It was some lyrics :)

About my case. The code have no external dependencies with React components. There is a helper in the code like I described above and the only way to check the type of element is using this helper (the helper is already exist). There is the only place in the code to fix this issue.

So for me, I would use `resolveType` if you exported it, at least as temporary quick solution.

If you decided to expose @lgra's solution as public it would be nice. At least it would be good start point, I think.

**Comment by theKashey** [comment] 2017-12-07 06:44
Anyway, even for the case with babel magic - method have to be exposed.

**Comment by alexey-kachalov** [comment] 2017-12-07 09:56
@theKashey sounds nice) We could kill two birds with one stone :)

**Comment by neoziro** [comment] 2017-12-25 12:06
Fixed in v4: https://github.com/gaearon/react-hot-loader/tree/next#checking-element-types

**Comment by alexey-kachalov** [comment] 2017-12-25 14:09
Nice to hear! =) Thanks guys!

**Comment by mmoutenot** [comment] 2018-02-07 17:28
@neoziro Thanks for the work on `areComponentsEqual`. 

How should one solve the issue where a third party dependency does this check? If `react-hot-loader` is imported at all it causes those checks to fail. This is noted [above](https://github.com/gaearon/react-hot-loader/issues/304#issuecomment-349828928), but I wasn't able to find a resolution in the ensuing conversations.

Thanks!

**Comment by neoziro** [comment] 2018-02-07 19:32
@mmoutenot good point! I don't have any solution yet. I think we will have to wait for React team to provide a Hot Reloading solution built in React.

**Comment by mmoutenot** [comment] 2018-02-07 19:40
Gotcha, it looks like some third party libraries are working to ensure things still work. Namely:

For example:
https://github.com/palantir/blueprint/issues/723
https://github.com/palantir/blueprint/issues/2095

**Comment by elado** [comment] 2018-02-28 20:44
@neoziro the current `areComponentsEqual` solution does not work with 3rd party libraries unless they change their code. Can this issue remain open until there's a better approach?

**Comment by theKashey** [comment] 2018-02-28 20:56
...this issue will remain open, but we don't have another soluting yet....

**Comment by alexey-kachalov** [comment] 2018-03-01 05:44
I don't know if babel can process 3rd party `node_modules`. If it can, we could try to write a plugin based on @lgra 's one which processes 3rd party modules using `areComponentsEqual`, I think.
It could be general solution. But there are performance issues in the case, I think.

**Comment by theKashey** [comment] 2018-03-01 05:49
It could. Even more - create-react-app already transpiling all the code, and RHL's babel plugin cound also safely extended to all the node_modules.
The problem - node_modules contain transpired JSX, and @lgra 's plugin will not work out of the box. And it much harder to create stable version, capable to work on transpiled, bundled, and uglified code. 

Volunteers?

**Comment by lgra** [comment] 2018-03-01 06:13
Maybe it's already been told, but here is my idea of the day, based on my use case.

RHL is a huge value when created our own code, or dealing with our own git submodules or npmised source packages, included as source JSX file. Using babel, it allows us to replace on the fly submodules file (for example css variable file) and insure our own code base to use common dependencies. The babel plugin I wrote perfectly fit this use case.

RHL is less value, even no value at all, when dealing with third parties transpiled npm modules.
Is it possible to make RHL proxified only our own classes, and let node_modules transpiled classes unchanged ?
A way to set what musn't be proxified could based on a vendor chunk defined in web pack config.

**Comment by theKashey** [comment] 2018-03-01 07:01
Not so fast :( We have no information about the origins of a class or file. We have some part of this information from `registration`, and they cover only "yours" code, but they dont see a lot components(HOC, decorated and so on).

The closest approach is to extend babel plugin to node_modules, and next handle classes from node_modules as something not going to be replaced.
Which is not always true, as long redux's connect should be handled.

The best approach for now - create a proposal to React team, to make thing more possible. If React will be more RHL friendly, RHL could be less aggressive to JS code.

**Comment by lgra** [comment] 2018-03-01 07:09
Understood.

**Comment by idubrov** [comment] 2018-05-24 18:40
Two questions:

There is no (easy) way to somehow tell RHL not to proxy certain components (using file path, component name, whatever)?

Also, there is no way to "unproxy" those components somehow (using some dirty trick or whatever)?

**Comment by theKashey** [comment] 2018-05-24 22:10
Hacks you said, @idubrov ?

```js
import reactHotLoader from 'react-hot-loader';

const originalCreateElement = React.createElement;
React.createElement =  (type, ...args) => {
   if(type should not be replaced){
      const oldValue =  reactHotLoader.disableProxyCreation;
      reactHotLoader.disableProxyCreation = true;
      const element = originalCreateElement(type, ...args)
      reactHotLoader.disableProxyCreation = oldValue;
      return element;
   } else {
          return originalCreateElement(type, ...args);
   }
};
```

**Comment by theKashey** [comment] 2018-05-24 22:38
You are right. RHL tries to hack React as soon as possible, and the only way to disable it - use `reactHotLoader.disableProxyCreation`. Which is a bit tricky flag, as long it will disable __creation__, but if something already got corresponding proxy - it will be returned.

**Comment by idubrov** [comment] 2018-05-25 00:47
Actually, that seems to do the the trick. I only use GraphiQL component in one place, so wrapping the place it is used in the following way:
```
ReactHotLoader.disableProxyCreation = true;
const result = (<GraphiQL>...</GraphiQL>);
ReactHotLoader.disableProxyCreation = false;
return result;
```
seems to solve my issue.

Thanks!

**Comment by idubrov** [comment] 2018-05-25 04:32
Would it be possible to have "nothot" function to mark components not to be proxable?

Like,
```
import { nothot } from "react-hot-loader";
import GraphiQL as GQL from "graphiql";

const GraphiQL = nothot(GQL);

...
```

**Comment by theKashey** [comment] 2018-05-25 05:02
Ok, so lets extract my latest proposal to completely _nothot__ node_modules into the separate issue https://github.com/gaearon/react-hot-loader/issues/991

**Comment by smelukov** [comment] 2018-10-01 18:39
Hi! Is proxy creation required for the correct working of RHL?
What if we'll always set `disableProxyCreation` to true?
Also, what if create `originalType` property for type comparison instead of `areComponentsEqual` and <Compoennt>.type?

**Comment by theKashey** [comment] 2018-10-02 00:41
RHL could not work without Proxies. Proxies are RHL.
But you can use `cold API` to disable proxy creation for any specific component.

**Comment by smelukov** [comment] 2018-10-02 10:07
@theKashey What do you think about creating `originalType` property (inside RHL) for type comparison instead of `areComponentsEqual` and `<Compoennt>.type`?

**Comment by theKashey** [comment] 2018-10-02 11:18
Then it would not work without RHL, in production, for example.

**Comment by smelukov** [comment] 2018-10-02 12:06
Of course, but in this case, we can implement the simplest implementation of `areComponentsEqual`:
```js
const aType = a.originalType || a.type;
const bType = b.originalType || b.type;

return aType === bType;
```

Without creating an element and getting an object behind a proxy.

**Comment by smelukov** [comment] 2018-10-02 12:18
We have a UI library (there are only UI components) and we compare instance types often inside of it to implement some rendering logic.
Now, we need to include `react-hot-loader` as a dependency for our library to use `areComponentsEqual` or we need to creating instances of the UI-components to get it's `type` property to compare with some other instance type.
We don't want to include `react-hot-loader` as a dependency.
And creating instances is not always available, cause some components have required props.

Would be great if RHL will add `originalType` prop and we'll can to compare instance types without requiring HRL and without creating an instance (example was posted above)

**Comment by theKashey** [comment] 2018-10-02 12:48
For __libraries__, which are not meant to change during developing, I would propose `cold api`. There is ongoing PR to use webpack loader to _cold_ all node_modules by default.

**Comment by smelukov** [comment] 2018-10-02 12:53
> use webpack loader to cold all node_modules by default

Seems like it will affect linked modules (`npm link`) and the changes in linked libraries will not be displayed. Right?

**Comment by theKashey** [comment] 2018-10-02 13:06
Yep. Could be a problem for monorepo. Right now we have something like this
```js
import { setConfig, cold } from 'react-hot-loader'

setConfig({
// this is for components defined on "top level" only
  onComponentRegister: (type, name, file) =>
    file.indexOf('node_modules') > 0 && cold(type),

// styled is created inside a function, we dont know the file name (probable doable using stack.js)
  onComponentCreate: (type, name) => name.indexOf('styled') > 0 && cold(type),
})
```
So the real "consumer" could have all the power upon freeze behavior, but not library itself.

**Comment by pitops** [comment] 2019-01-14 08:57
@theKashey Any workaround suggestions for monorepos?

**Comment by theKashey** [comment] 2019-01-17 09:48
@pitops - `hot-loader/react-dom`(or webpack plugin) to solve type comparison for SFCs only.

v5 would solve this issue next month.

**Comment by wijdench** [comment] 2019-01-21 04:10
Hi,
Same issue for me, hope that v5 release will be soon.

**Comment by joanned** [comment] 2019-01-22 18:36
Same issue as well.

**Comment by carloseduardosx** [comment] 2019-05-31 04:37
The @JorgenEvens solution worked pretty well for me, although I did just a minor improvement:

```jsx
const ImportedComponent = (props) => { ... }

const element = <ImportedComponent />
console.log(element.type === ImportedComponent)
```

The type of the instantiated component is basically a reference to the component itself, so the above approach works fine.

**Comment by theKashey** [comment] 2019-05-31 05:46
It would print "false". That's the problem.

**Comment by carloseduardosx** [comment] 2019-05-31 13:12
@theKAre you sure? I tested yesterday in my project, in my example above I'm comparing the type with the component function, not with the instantiated component, that's the reason why it works.

**Comment by theKashey** [comment] 2019-06-02 02:55
v4.10.0(beta) with a patch to `react-dom` landed by __webpack plugin__(refer to docs) would FIX THIS ISSUE.
Just a two years later. Give it a try.

**Closed** 2019-06-10 01:19 UTC
Labels: enhancement

**Comment by theKashey** [comment] 2019-09-23 22:12
@RobertGary1 - works only with `hot-loader/react-dom` integration. Not working without.
