### ISSUE TITLE
window.setTimeout not triggering?

### ISSUE THREAD

**Issue by WishCow** [gaearon/react-hot-loader#94] opened 2015-03-07 22:43 UTC
Is it possible that react-hot-loader somehow blocks window.setTimeout()? I have this piece of code:

```js
window.setTimeout(function() {
    alert('hi');
}, 3000);
```

and this only fires once, in the sense that if I reload the page, it will not trigger again, as long as the hot loader server is running. If I kill the server with ctrl-c, and then restart it, I see the alert again, once, and it never comes up until I kill the server again. If I do not start the server at all, it works every time I refresh the browser.

**Comment by gaearon** [comment] 2015-03-07 23:13
I can't reproduce this. Could your browser be blocking additional alerts from the same page?

**Comment by WishCow** [comment] 2015-03-08 00:40
No, a console.log doesn't show up either.

It works fine in Chrome, but Firefox (36.0) doesn't trigger it.

**Comment by gaearon** [comment] 2015-03-08 01:17
Is this related to RHL? If you remove react-hot from loaders, does the problem disappear?

**Comment by gaearon** [comment] 2015-03-09 20:44
Please let me know if you can share a reproducible example! Either way, it's highly unlikely that RHL is messing with `setTimeout`. I'm closing for now but let me know if you can give me a way to repro this.

**Closed by gaearon** 2015-03-09 20:44 UTC

**Comment by johnloy** [comment] 2015-09-06 13:57
This seems to be happening to me as well, though I also couldn't tell you how to reproduce it. `setTimeout` should just work, and for whatever bizarre reason it's simply not. With webpack, babel, and RHL magic going on under the hood, I don't even know where to begin to troubleshoot.

**Comment by johnloy** [comment] 2015-09-06 14:04
Ok, I just realized it's only not working when the document is loading, if that provides any kind of clue.

**Comment by Pierozi** [comment] 2016-05-15 14:26
I have the same issue on firefox v45. not Chrome.
`setTimeout` callback has not fired even after page loading when i try with console through firebug or firefox devtool.

I can confirm the problem disappear with i **disable or remove hot-loader in webpack**.
