### ISSUE TITLE
use `react-hot-loader/patch`,I can't setState in function that bind 'this' in constructor

### ISSUE THREAD

**Issue by ibyh** [gaearon/react-hot-loader#597] opened 2017-06-27 10:03 UTC
### Description
When I use react-hot-loader,I put the `react-hot-loader/patch` in the first line of the entry `index` file,then in the `app` file,I create one react Component which only has 2 input.the difference of the 2 inputs is that one bind an `onChange` function which bind `this` in the `constructor` and another input bind an `onChange` function which bind `this` in `render`.I expect that the 2 input has the same behavior,but not so in real.the input bind `onChange` function which bind `this` in `constructor` got an error `setState(...): Can only update a mounted or mounting component. `

But when i remove the `react-hot-loader/patch` from the entry file,the 2 input has the same behavior.I don't know why it is this.

### Expected behavior

a react component bind an event function that bind `this` in `constructor` can call `setState` correactly

### Actual behavior

when a react component bind an event function that bind `this` in `constructor` ,when i call setState,it throw an error `Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the _default component.`

### Environment

React Hot Loader version:3.0.0-beta.7

Run these commands in the project folder and fill in their results:

1. `node -v`:7.9.0
2. `npm -v`:4.2.0
3. Operating system:Win10 64-bit
4. Browser and version:Chrome 59

### Reproducible Demo
[react-hot-loader-bind-this-test](https://github.com/ibyh/react-hot-loader-bind-this-test)

**Comment by smikitky** [comment] 2017-06-29 08:06
I think this is a duplicate of #313. This occurs when you are targeting only at recent browsers with native `class` support. To work around this, try manually enabling `transform-es2015-classes` plugin in your `.babelrc`.

**Comment by ChuckJonas** [comment] 2017-09-19 15:01
I'm having the same issue. Targeting ES6

**Comment by neoziro** [comment] 2017-09-19 19:39
I know this bug, we have to add a test for it. It is relative to babel plugin that doesn't work with native `class`. Help welcome.

**Comment by neoziro** [comment] 2017-09-19 19:40
I close it because it's a duplicate of #313

**Closed by neoziro** 2017-09-19 19:40 UTC
