### ISSUE TITLE
flux-hot-reload?

### ISSUE THREAD

**Issue by ronag** [gaearon/react-hot-loader#30] opened 2014-09-21 07:55 UTC
This is more of a question. Do you think we could apply parts of this technology to flux? e.g. having flux stores be hot-reloaded? I guess that would require some kind of API on the stores, e.g. a "reset" method so that the stores can be notified of the hot reload.

Any thoughts or suggestions on this?

**Comment by nivoc** [comment] 2015-01-23 22:14
Any update since then? My store/s get hot-reloaded but the Problem is that the old store is still there and still registered to the dispatcher callbacks... so after a hot-reload both stores react on the actions. I have some hacky ways in mind to solve it - but :-)

Is there any non-hacky way already?

**Comment by gaearon** [comment] 2015-01-23 23:22
I plan to take a look at this ~ in a month.

**Comment by gaearon** [comment] 2015-01-29 23:36
I have some progress. This is *very* sketchy at the moment, not on NPM and can work only with FB's vanilla Flux (Facebook's `flux` dispatcher and `EventEmitter` stores):

https://github.com/gaearon/flux-hot-loader

If you feel like giving it a try, put this in `node_modules` manually and add something like this next to `react-hot` in Webpack config:

```js
{ test: /\.jsx?$/, loader: 'flux-hot?dispatcher=../dispatcher/AppDispatcher', include: /scripts\/stores/ }
```

where `include` is regexp for directory with your Flux Stores and `dispatcher` is path to the global dispatcher from any file in that directory.

One hard condition right now is that each Store must have a property called `dispatchToken` that is equal to `AppDispatcher.register` return value.

**Comment by gaearon** [comment] 2015-01-29 23:40
Note: it's quite possible that this only works in Manual mode (`react-hot?manual`). I haven't even documented the manual mode yet because I'm waiting for React Router 0.12 with `router.replaceRoutes` to be released :-)

**Comment by VesQ** [comment] 2015-01-30 09:59
Looks promising! I doubt that it will work with ES6 modules, though — the [`6to5` loader](https://github.com/6to5/6to5-loader) we're using happens to export definitions such as `export default MyDispatcher;` to `module.exports.default` and the stores which are exported in our app use the same `export default MyStore;` syntax.

I'm not fully aware how other ES6 transpilers/loaders/what have you set variables to CommonJS `module.exports`, but I'd suppose it won't be such a big leap to support finding exports from `module.exports` and `module.exports.default` should it be available.

If I export ES6 `6to5` modules via `export var MyVariable` or something else besides the `export default Foo`, they will get properly assigned to `module.exports.MyVariable`.

I could give it a try with our setup if it would support these things.

**Comment by gaearon** [comment] 2015-01-30 11:49
Thanks for the tip, I'll add support for `default`.

**Comment by gaearon** [comment] 2015-05-11 00:15
I'm going to go with a different solution to this. It's more fundamentally solid.
I'm closing this issue for now, but expect to see something working in a month or two!

**Closed by gaearon** 2015-05-11 00:15 UTC
