### ISSUE TITLE
[3.0] react-hot-loader breaks react-art

### ISSUE THREAD

**Issue by jkeljo** [gaearon/react-hot-loader#317] opened 2016-07-04 23:24 UTC
See repro case at https://github.com/jkeljo/react-hot-loader-and-art-bug. Tested in Chrome  51.0.2704.103 (64-bit) on OSX.

**Comment by calesce** [comment] 2016-09-15 02:46
Thanks for the simple project, I was also able to reproduce. This is definitely a problem with RHL. I'm not familiar with React-ART, but since it uses React internals, it might break some assumptions that React Hot Loader makes.

**Comment by neoziro** [comment] 2017-12-25 12:25
[Upgraded all things](https://github.com/neoziro/react-hot-loader-and-art-bug) and it seems to be fixed with [v4](https://github.com/gaearon/react-hot-loader/tree).

**Closed** 2018-02-27 10:08 UTC
Labels: bug, fixed in next
